# Combined single-origin image: builds the React SPA and serves it from the API
# server (SERVE_STATIC_DIR=/app/public). One container, one origin, one
# Cloudflare Access policy. This is the image the Railway dev environment uses.
#
# Split mode (SPA and API on separate hosts) had two images here until #1456
# deleted them unbuilt: single-origin is a commitment, not a default. The
# image builds from the REPO ROOT context so the npm-workspaces install can
# link packages/* (shared-types, #820): root
# manifests + packages/ first (cache-friendly — they change rarely), then
# `npm ci --workspace <ws>` against the single root lockfile, then sources.

# 1. Build the SPA with a relative API base so it talks to the same origin.
FROM node:22-alpine AS frontend
WORKDIR /app
# Root lockfile was generated by npm 11 — align the CLI like CI does (npm/cli#4828).
RUN npm install -g npm@11
COPY package.json package-lock.json ./
COPY packages/ packages/
COPY frontend/package.json frontend/
RUN npm ci --workspace frontend
COPY frontend/ frontend/
WORKDIR /app/frontend
ENV VITE_API_URL=/api
RUN npm run build

# 2. Build the backend: install deps, generate the Prisma client, compile TS.
FROM node:22-alpine AS backend
WORKDIR /app
RUN npm install -g npm@11
COPY package.json package-lock.json ./
COPY packages/ packages/
COPY backend/package.json backend/
RUN npm ci --workspace backend
# packages/contracts compiles to JS because the backend imports its zod schemas
# as VALUES and node:22-alpine cannot execute a .ts (#1370). .dockerignore drops
# **/dist, so the host's build never leaks in — this line is the only thing that
# puts dist/ in the image, and stage 3's `COPY --from=backend /app /app` carries it.
# The load assertion walks EVERY *Schema export rather than spot-checking one, so
# a barrel that drops a schema fails the image build instead of at first request;
# the count guard keeps an empty barrel from passing vacuously — it must be
# raised to the tree's real export count whenever a family is added, or a barrel
# that loads only the old subset passes for the wrong reason.
RUN npm run build --workspace @character-sheet/contracts \
 && node --input-type=module -e "import('@character-sheet/contracts').then(m => { const s = Object.keys(m).filter(k => k.endsWith('Schema')); if (s.length < 15 || s.some(k => typeof m[k]?.parse !== 'function')) { console.error('contracts barrel failed to load:', s.length, 'schemas'); process.exit(1); } console.log('contracts:', s.length, 'schemas loaded'); })"
COPY backend/ backend/
WORKDIR /app/backend
# prisma.config.ts resolves env("DATABASE_URL") when the CLI loads it, so a
# placeholder is required even though `generate` never connects to a database.
RUN DATABASE_URL="postgresql://build:build@localhost:5432/build" npx prisma generate && npm run build

# 3. Runtime: the backend workspace tree (root node_modules carries the deps,
# incl. the Prisma CLI + tsx needed by migrate/seed) plus the built SPA served
# as static files.
FROM node:22-alpine
WORKDIR /app/backend
COPY --from=backend /app /app
COPY --from=frontend /app/frontend/dist /app/public
ENV SERVE_STATIC_DIR=/app/public
ENV PORT=4000
EXPOSE 4000
# Apply migrations, run the seed, then start the server. The seed is idempotent
# (upserts only, catalog/reference data) so running it on every container start
# is safe; it adds a little startup latency but keeps reference data current.
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && node dist/index.js"]
