// Pure 5e catalog seed data — no Prisma, no side effects; 5e rules math
// lives in src/lib, not here.

// Relative, not @/ — the seed's tsx context doesn't alias.
import type {
  ItemCategory,
  ToolCategory,
  WeaponDetailInput,
  ArmorDetailInput,
  ConsumableDetailInput,
} from "../../src/lib/inventory/item-detail-inputs.js";
import type { SeedEdition } from "./edition.js";

// armorProficiencies/weaponProficiencies: SRD 5.1/PHB'14 only (2014 and 2024
// diverge for at least Bard/Druid/Monk/Rogue/Sorcerer/Wizard, #1548).
// extraAsiLevels/multiclassPrerequisites: PHB'14 p.163 / PHB'14 p.38 (both
// editions agree). primaryAbilities: PHB'24 by-class table (no 2014
// equivalent).
export const CLASSES = [
  {
    name: "Wizard",
    hitDie: "d6",
    savingThrows: ["intelligence", "wisdom"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "history", "insight", "investigation", "medicine", "religion"],
    isSpellcaster: true,
    subclassLevel: 2, // PHB'14 p. 114: Arcane Tradition at 2nd level.
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ intelligence: 13 }],
    primaryAbilities: ["intelligence"],
  },
  {
    name: "Fighter",
    hitDie: "d10",
    savingThrows: ["strength", "constitution"],
    skillChoiceCount: 2,
    skillChoices: [
      "acrobatics",
      "animalHandling",
      "athletics",
      "history",
      "insight",
      "intimidation",
      "perception",
      "survival",
    ],
    isSpellcaster: false,
    subclassLevel: 3,
    armorProficiencies: ["light", "medium", "heavy", "shield"],
    weaponProficiencies: ["Simple Weapons", "Martial Weapons"],
    extraAsiLevels: [6, 14],
    fightingStyleFeatLevel: 1,
    // Fighter is the only OR class: Str 13 OR Dex 13.
    multiclassPrerequisites: [{ strength: 13 }, { dexterity: 13 }],
    primaryAbilities: ["strength", "dexterity"],
  },
  {
    name: "Rogue",
    hitDie: "d8",
    savingThrows: ["dexterity", "intelligence"],
    skillChoiceCount: 4,
    skillChoices: [
      "acrobatics",
      "athletics",
      "deception",
      "insight",
      "intimidation",
      "investigation",
      "perception",
      "performance",
      "persuasion",
      "sleightOfHand",
      "stealth",
    ],
    isSpellcaster: false,
    subclassLevel: 3,
    toolProficiencies: ["Thieves' Tools"],
    armorProficiencies: ["light"],
    weaponProficiencies: ["Simple Weapons", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    extraAsiLevels: [10],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ dexterity: 13 }],
    primaryAbilities: ["dexterity"],
  },
  {
    name: "Cleric",
    hitDie: "d8",
    savingThrows: ["wisdom", "charisma"],
    skillChoiceCount: 2,
    skillChoices: ["history", "insight", "medicine", "persuasion", "religion"],
    isSpellcaster: true,
    subclassLevel: 1, // PHB'14 p. 57: Divine Domain at 1st level.
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: ["Simple Weapons"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ wisdom: 13 }],
    primaryAbilities: ["wisdom"],
  },
  {
    name: "Barbarian",
    hitDie: "d12",
    savingThrows: ["strength", "constitution"],
    skillChoiceCount: 2,
    skillChoices: ["animalHandling", "athletics", "intimidation", "nature", "perception", "survival"],
    isSpellcaster: false,
    subclassLevel: 3,
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: ["Simple Weapons", "Martial Weapons"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ strength: 13 }],
    primaryAbilities: ["strength"],
  },
  {
    name: "Bard",
    hitDie: "d8",
    savingThrows: ["dexterity", "charisma"],
    skillChoiceCount: 3,
    skillChoices: [
      "acrobatics",
      "animalHandling",
      "arcana",
      "athletics",
      "deception",
      "history",
      "insight",
      "intimidation",
      "investigation",
      "medicine",
      "nature",
      "perception",
      "performance",
      "persuasion",
      "religion",
      "sleightOfHand",
      "stealth",
      "survival",
    ],
    isSpellcaster: true,
    subclassLevel: 3,
    // PHB: Three musical instruments of your choice.
    toolChoiceCount: 3,
    toolChoices: [
      "Bagpipes", "Drum", "Dulcimer", "Flute", "Lute",
      "Lyre", "Horn", "Pan Flute", "Shawm", "Viol",
    ],
    armorProficiencies: ["light"],
    weaponProficiencies: ["Simple Weapons", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ charisma: 13 }],
    primaryAbilities: ["charisma"],
  },
  {
    name: "Druid",
    hitDie: "d8",
    savingThrows: ["intelligence", "wisdom"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "animalHandling", "insight", "medicine", "nature", "perception", "religion", "survival"],
    isSpellcaster: true,
    subclassLevel: 2, // PHB'14 p. 66: Druid Circle at 2nd level.
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: [
      "Clubs", "Daggers", "Darts", "Javelins", "Maces", "Quarterstaffs",
      "Scimitars", "Sickles", "Slings", "Spears",
    ],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ wisdom: 13 }],
    primaryAbilities: ["wisdom"],
  },
  {
    name: "Monk",
    hitDie: "d8",
    savingThrows: ["strength", "dexterity"],
    skillChoiceCount: 2,
    skillChoices: ["acrobatics", "athletics", "history", "insight", "religion", "stealth"],
    isSpellcaster: false,
    subclassLevel: 3,
    // PHB: One type of artisan's tools or one musical instrument of your choice.
    toolChoiceCount: 1,
    toolChoices: [
      "Alchemist's Supplies", "Brewer's Supplies", "Calligrapher's Supplies",
      "Carpenter's Tools", "Cartographer's Tools", "Cobbler's Tools",
      "Cook's Utensils", "Glassblower's Tools", "Jeweler's Tools",
      "Leatherworker's Tools", "Mason's Tools", "Painter's Supplies",
      "Potter's Tools", "Smith's Tools", "Tinker's Tools",
      "Weaver's Tools", "Woodcarver's Tools",
      "Bagpipes", "Drum", "Dulcimer", "Flute", "Lute",
      "Lyre", "Horn", "Pan Flute", "Shawm", "Viol",
    ],
    armorProficiencies: [],
    weaponProficiencies: ["Simple Weapons", "Shortswords"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ dexterity: 13, wisdom: 13 }],
    primaryAbilities: ["dexterity", "wisdom"],
  },
  {
    name: "Paladin",
    hitDie: "d10",
    savingThrows: ["wisdom", "charisma"],
    skillChoiceCount: 2,
    skillChoices: ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"],
    isSpellcaster: true,
    subclassLevel: 3,
    armorProficiencies: ["light", "medium", "heavy", "shield"],
    weaponProficiencies: ["Simple Weapons", "Martial Weapons"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: 2,
    multiclassPrerequisites: [{ strength: 13, charisma: 13 }],
    primaryAbilities: ["strength", "charisma"],
  },
  {
    name: "Ranger",
    hitDie: "d10",
    savingThrows: ["strength", "dexterity"],
    skillChoiceCount: 3,
    skillChoices: ["animalHandling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"],
    isSpellcaster: true,
    subclassLevel: 3,
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: ["Simple Weapons", "Martial Weapons"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: 2,
    multiclassPrerequisites: [{ dexterity: 13, wisdom: 13 }],
    primaryAbilities: ["dexterity", "wisdom"],
  },
  {
    name: "Sorcerer",
    hitDie: "d6",
    savingThrows: ["constitution", "charisma"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"],
    isSpellcaster: true,
    subclassLevel: 1, // PHB'14 p. 99: Sorcerous Origin at 1st level.
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ charisma: 13 }],
    primaryAbilities: ["charisma"],
  },
  {
    name: "Warlock",
    hitDie: "d8",
    savingThrows: ["wisdom", "charisma"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"],
    isSpellcaster: true,
    subclassLevel: 1, // PHB'14 p. 105: Otherworldly Patron at 1st level.
    armorProficiencies: ["light"],
    weaponProficiencies: ["Simple Weapons"],
    extraAsiLevels: [],
    fightingStyleFeatLevel: null,
    multiclassPrerequisites: [{ charisma: 13 }],
    primaryAbilities: ["charisma"],
  },
];

// SRD 5.2 for the four SRD rows; PHB'24 for Charlatan/Noble; PHB'14-only
// Folk Hero. abilityChoices/originFeatName are 2024-only concepts, so a row
// omitting both IS the 2014 row.
export interface BackgroundSeed {
  name: string;
  skillProficiencies: string[];
  toolProficiencies?: string[];
  // Mirrors ClassSeed's toolChoices/toolChoiceCount. Omitted = no choice,
  // same convention as toolProficiencies.
  toolChoices?: string[];
  toolChoiceCount?: number;
  abilityChoices?: string[];
  originFeatName?: string;
  // Omitted = shared (NULL column, valid in both editions, #1306).
  edition?: SeedEdition;
}

export const BACKGROUNDS: BackgroundSeed[] = [
  { name: "Sage",      skillProficiencies: ["arcana", "history"],
    abilityChoices: ["constitution", "intelligence", "wisdom"],
    originFeatName: "Magic Initiate", toolProficiencies: ["Calligrapher's Supplies"] },
  // Soldier/Noble's tool line is "one type of Gaming Set" in both PHB'14 and
  // PHB'24 — a CHOICE. starting-equipment.ts's SOLDIER_2024/NOBLE_2024
  // (boundToToolChoice: true) depends on this choice existing.
  { name: "Soldier",   skillProficiencies: ["athletics", "intimidation"],
    abilityChoices: ["strength", "dexterity", "constitution"],
    originFeatName: "Savage Attacker",
    toolChoices: ["Dice Set", "Dragonchess Set", "Playing Card Set", "Three-Dragon Ante Set"],
    toolChoiceCount: 1 },
  { name: "Charlatan", skillProficiencies: ["deception", "sleightOfHand"],
    abilityChoices: ["dexterity", "constitution", "charisma"],
    originFeatName: "Skilled", toolProficiencies: ["Forgery Kit"] },
  { name: "Acolyte",   skillProficiencies: ["insight", "religion"],
    abilityChoices: ["intelligence", "wisdom", "charisma"],
    originFeatName: "Magic Initiate", toolProficiencies: ["Calligrapher's Supplies"] },
  { name: "Criminal",  skillProficiencies: ["sleightOfHand", "stealth"],
    abilityChoices: ["dexterity", "constitution", "intelligence"],
    originFeatName: "Alert", toolProficiencies: ["Thieves' Tools"] },
  // PHB'14 only — PHB'24 has no Folk Hero (#1570). Retagged in place by a
  // migration; delete-and-recreate would strand characters holding it
  // (CharacterBackground.backgroundId is SetNull).
  { name: "Folk Hero", skillProficiencies: ["animalHandling", "survival"], edition: "EDITION_2014" },
  // Same Gaming Set choice as Soldier (#1779).
  { name: "Noble",     skillProficiencies: ["history", "persuasion"],
    abilityChoices: ["strength", "intelligence", "charisma"],
    originFeatName: "Skilled",
    toolChoices: ["Dice Set", "Dragonchess Set", "Playing Card Set", "Three-Dragon Ante Set"],
    toolChoiceCount: 1 },
];

function coins(gp: number, sp = 0, cp = 0) {
  return { cp, sp, gp, pp: 0 };
}

export interface CatalogItem {
  name: string;
  category: ItemCategory;
  weight?: number;
  cost?: ReturnType<typeof coins>;
  description?: string;
  weapon?: WeaponDetailInput;
  armor?: ArmorDetailInput;
  consumable?: ConsumableDetailInput;
  // Set only for rows that ARE tools, so a starting-equipment open pick can
  // filter on it as a column (#1564).
  toolCategory?: ToolCategory;
}

// This seeds the catalog rows InventoryItem snapshots from at pick time (see
// schema.prisma's Item/InventoryItem comment for why snapshot, not live
// reference).
export const ITEMS: CatalogItem[] = [
  {
    name: "Club",
    category: "weapon",
    weight: 2,
    cost: coins(0, 1),
    weapon: { damageDiceCount: 1, damageDiceFaces: 4, damageType: "bludgeoning", light: true, weaponClass: "simple", weaponRange: "melee" },
  },
  {
    name: "Dagger",
    category: "weapon",
    weight: 1,
    cost: coins(2),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 4,
      damageType: "piercing",
      finesse: true,
      light: true,
      thrown: true,
      rangeNormal: 20,
      rangeLong: 60,
      weaponClass: "simple",
      weaponRange: "melee",
    },
  },
  {
    name: "Quarterstaff",
    category: "weapon",
    weight: 4,
    cost: coins(0, 2),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 6,
      damageType: "bludgeoning",
      versatileDiceCount: 1,
      versatileDiceFaces: 8,
      weaponClass: "simple",
      weaponRange: "melee",
    },
  },
  {
    name: "Mace",
    category: "weapon",
    weight: 4,
    cost: coins(5),
    weapon: { damageDiceCount: 1, damageDiceFaces: 6, damageType: "bludgeoning", weaponClass: "simple", weaponRange: "melee" },
  },
  {
    name: "Javelin",
    category: "weapon",
    weight: 2,
    cost: coins(0, 5),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 6,
      damageType: "piercing",
      thrown: true,
      rangeNormal: 30,
      rangeLong: 120,
      weaponClass: "simple",
      weaponRange: "melee",
    },
  },
  {
    name: "Light Crossbow",
    category: "weapon",
    weight: 5,
    cost: coins(25),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 8,
      damageType: "piercing",
      ammunition: true,
      twoHanded: true,
      rangeNormal: 80,
      rangeLong: 320,
      weaponClass: "simple",
      weaponRange: "ranged",
    },
  },
  {
    name: "Shortbow",
    category: "weapon",
    weight: 2,
    cost: coins(25),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 6,
      damageType: "piercing",
      ammunition: true,
      twoHanded: true,
      rangeNormal: 80,
      rangeLong: 320,
      weaponClass: "simple",
      weaponRange: "ranged",
    },
  },
  {
    name: "Shortsword",
    category: "weapon",
    weight: 2,
    cost: coins(10),
    weapon: { damageDiceCount: 1, damageDiceFaces: 6, damageType: "piercing", finesse: true, light: true, weaponClass: "martial", weaponRange: "melee" },
  },
  {
    name: "Longsword",
    category: "weapon",
    weight: 3,
    cost: coins(15),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 8,
      damageType: "slashing",
      versatileDiceCount: 1,
      versatileDiceFaces: 10,
      weaponClass: "martial",
      weaponRange: "melee",
    },
  },
  {
    name: "Rapier",
    category: "weapon",
    weight: 2,
    cost: coins(25),
    weapon: { damageDiceCount: 1, damageDiceFaces: 8, damageType: "piercing", finesse: true, weaponClass: "martial", weaponRange: "melee" },
  },
  {
    name: "Warhammer",
    category: "weapon",
    weight: 2,
    cost: coins(15),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 8,
      damageType: "bludgeoning",
      versatileDiceCount: 1,
      versatileDiceFaces: 10,
      weaponClass: "martial",
      weaponRange: "melee",
    },
  },
  {
    name: "Handaxe",
    category: "weapon",
    weight: 2,
    cost: coins(5),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 6,
      damageType: "slashing",
      light: true,
      thrown: true,
      rangeNormal: 20,
      rangeLong: 60,
      weaponClass: "martial",
      weaponRange: "melee",
    },
  },
  {
    name: "Greataxe",
    category: "weapon",
    weight: 7,
    cost: coins(30),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 12,
      damageType: "slashing",
      heavy: true,
      twoHanded: true,
      weaponClass: "martial",
      weaponRange: "melee",
    },
  },
  {
    name: "Longbow",
    category: "weapon",
    weight: 2,
    cost: coins(50),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 8,
      damageType: "piercing",
      ammunition: true,
      heavy: true,
      twoHanded: true,
      rangeNormal: 150,
      rangeLong: 600,
      weaponClass: "martial",
      weaponRange: "ranged",
    },
  },
  {
    name: "Leather Armor",
    category: "armor",
    weight: 10,
    cost: coins(10),
    armor: { armorCategory: "light", baseArmorClass: 11, dexModifierApplies: true },
  },
  {
    name: "Scale Mail",
    category: "armor",
    weight: 45,
    cost: coins(50),
    armor: { armorCategory: "medium", baseArmorClass: 14, dexModifierApplies: true, dexModifierMax: 2, stealthDisadvantage: true },
  },
  {
    name: "Chain Mail",
    category: "armor",
    weight: 55,
    cost: coins(75),
    armor: { armorCategory: "heavy", baseArmorClass: 16, stealthDisadvantage: true, strengthRequirement: 13 },
  },
  {
    name: "Shield",
    category: "armor",
    weight: 6,
    cost: coins(10),
    description: "Worn on one arm; grants +2 AC while wielded.",
    armor: { armorCategory: "shield", baseArmorClass: 2 },
  },
  {
    name: "Plate Armor",
    category: "armor",
    weight: 65,
    cost: coins(1500),
    armor: { armorCategory: "heavy", baseArmorClass: 18, stealthDisadvantage: true, strengthRequirement: 15 },
  },
  {
    name: "Potion of Healing",
    category: "consumable",
    weight: 0.5,
    cost: coins(50),
    consumable: { effectDiceCount: 2, effectDiceFaces: 4, effectModifier: 2, effectDescription: "Restores hit points" },
  },
  {
    name: "Caltrops",
    category: "consumable",
    weight: 2,
    cost: coins(1),
    description: "Covers a 5-ft square. A creature entering must succeed a DC 15 Dex save or take 1 piercing damage and stop moving for the rest of its turn.",
  },
  { name: "Arrows", category: "gear", weight: 0.05, cost: coins(0, 5, 0), description: "A quiver of 20 arrows. Price is per arrow." },
  { name: "Crossbow Bolts", category: "gear", weight: 0.075, cost: coins(0, 5, 0), description: "A case of 20 bolts. Price is per bolt." },
  { name: "Spellbook", category: "gear", weight: 3, cost: coins(50) },
  { name: "Component Pouch", category: "gear", weight: 2, cost: coins(25), description: "A small watertight pouch holding what a spellcaster needs to cast spells with material components." },
  { name: "Pearl (arcane focus)", category: "gear", weight: 0.1, cost: coins(100), description: "Used by a spellcaster as an arcane focus in place of components." },
  { name: "Holy Symbol", category: "gear", weight: 1, cost: coins(5), description: "An amulet, reliquary, or other symbol of a deity. Clerics and paladins use this as a spellcasting focus." },
  { name: "Lute", category: "gear", weight: 2, cost: coins(35), description: "A musical instrument; bards use it as a spellcasting focus.", toolCategory: "musicalInstrument" },
  { name: "Thieves' Tools", category: "gear", weight: 1, cost: coins(25), description: "Lockpicks, a small file, mirror, scissors, and tweezers.", toolCategory: "other" },
  { name: "Ink and Quill", category: "gear", cost: coins(10) },
  { name: "Healer's Kit", category: "gear", weight: 3, cost: coins(5), description: "Has 10 uses. As an action, expend one use to stabilize a creature without a Wisdom (Medicine) check." },
  { name: "Dungeoneer's Pack", category: "gear", weight: 61.5, cost: coins(12), description: "Includes a backpack, a crowbar, a hammer, 10 pitons, 10 torches, a tinderbox, 10 days of rations, a waterskin, and 50 ft of hempen rope." },
  { name: "Explorer's Pack", category: "gear", weight: 59, cost: coins(10), description: "Includes a backpack, a bedroll, a mess kit, a tinderbox, 10 torches, 10 days of rations, a waterskin, and 50 ft of hempen rope." },
  { name: "Burglar's Pack", category: "gear", weight: 44.5, cost: coins(16), description: "Includes a backpack, ball bearings (1000), 10 ft of string, a bell, 5 candles, a crowbar, a hammer, 10 pitons, a hooded lantern, 2 flasks of oil, 5 days of rations, a tinderbox, a waterskin, and 50 ft of hempen rope." },
  { name: "Priest's Pack", category: "gear", weight: 24, cost: coins(19), description: "Includes a backpack, a blanket, 10 candles, a tinderbox, an alms box, 2 blocks of incense, a censer, vestments, 2 days of rations, and a waterskin." },
  { name: "Diplomat's Pack", category: "gear", weight: 36, cost: coins(39), description: "Includes a chest, 2 cases for maps and scrolls, a set of fine clothes, a bottle of ink, an ink pen, a lamp, 2 flasks of oil, 5 sheets of paper, a vial of perfume, sealing wax, and soap." },
  { name: "Entertainer's Pack", category: "gear", weight: 38, cost: coins(40), description: "Includes a backpack, a bedroll, 2 costumes, 5 candles, 5 days of rations, a waterskin, and a disguise kit." },
  { name: "Scholar's Pack", category: "gear", weight: 11, cost: coins(40), description: "Includes a backpack, a book of lore, a bottle of ink, an ink pen, 10 sheets of parchment, a little bag of sand, and a small knife." },
  { name: "Backpack", category: "gear", weight: 5, cost: coins(2) },
  { name: "Crowbar", category: "gear", weight: 5, cost: coins(2) },
  { name: "Hammer", category: "gear", weight: 3, cost: coins(1) },
  { name: "Piton", category: "gear", weight: 0.25, cost: coins(0, 5, 0) },
  { name: "Torch", category: "gear", weight: 1, cost: coins(0, 1, 0), description: "Burns for 1 hour; bright light in 20 ft, dim 20 ft beyond. Can be used as an improvised weapon (1 fire damage)." },
  { name: "Tinderbox", category: "gear", weight: 1, cost: coins(0, 5, 0), description: "Used to light fires; takes an action to light a torch or similar." },
  { name: "Rations", category: "gear", weight: 2, cost: coins(0, 5, 0), description: "Dry foods suitable for extended travel." },
  { name: "Waterskin", category: "gear", weight: 5, cost: coins(0, 2, 0), description: "Holds up to 4 pints of liquid. Weight includes 4 pints of water." },
  { name: "Hempen Rope (50 ft)", category: "gear", weight: 10, cost: coins(1) },
  { name: "Bedroll", category: "gear", weight: 7, cost: coins(1) },
  { name: "Mess Kit", category: "gear", weight: 1, cost: coins(0, 2, 0), description: "Tin box with a cup and simple cutlery." },
  { name: "Ball Bearings", category: "gear", weight: 2, cost: coins(1), description: "As an action, scatter up to 1000 ball bearings (included) from a pouch across a 10-ft square. Creatures moving through must succeed DC 10 Dex or fall prone." },
  { name: "String (10 ft)", category: "gear", cost: coins(0, 0, 1) },
  { name: "Bell", category: "gear", weight: 0.1, cost: coins(1) },
  { name: "Candle", category: "gear", weight: 0.01, cost: coins(0, 0, 1), description: "Dim light in 5 ft for 1 hour." },
  { name: "Hooded Lantern", category: "gear", weight: 2, cost: coins(5), description: "Bright light in 30 ft and dim light for 30 ft beyond, or dim light in a 5-ft cone (hood closed). Burns for 6 hours per flask of oil." },
  { name: "Oil Flask", category: "consumable", weight: 1, cost: coins(0, 1, 0), description: "Fuels a lantern for 6 hours. Can be splashed on a surface or creature (DC 10 Dex, sets alight for 1d4 fire per round)." },
  { name: "Blanket", category: "gear", weight: 3, cost: coins(0, 5, 0) },
  { name: "Alms Box", category: "gear", weight: 1, cost: coins(0, 5, 0) },
  { name: "Incense Block", category: "gear", weight: 0.1, cost: coins(0, 2, 0) },
  { name: "Censer", category: "gear", weight: 2, cost: coins(5) },
  { name: "Vestments", category: "gear", weight: 4, cost: coins(5) },
  { name: "Chest", category: "gear", weight: 25, cost: coins(5), description: "Holds 300 lb / 12 cubic feet." },
  { name: "Map Case", category: "gear", weight: 1, cost: coins(1), description: "Scroll or map case; holds 10 rolled documents." },
  { name: "Fine Clothes", category: "gear", weight: 6, cost: coins(15) },
  { name: "Lamp", category: "gear", weight: 1, cost: coins(0, 5, 0), description: "Bright light in 15 ft, dim light 30 ft beyond. Burns for 6 hours per flask of oil." },
  { name: "Paper Sheet", category: "gear", weight: 0, cost: coins(0, 2, 0) },
  { name: "Perfume Vial", category: "gear", weight: 0, cost: coins(5) },
  { name: "Sealing Wax", category: "gear", weight: 0, cost: coins(0, 5, 0) },
  { name: "Soap", category: "gear", weight: 0, cost: coins(0, 0, 2) },
  { name: "Costume Clothes", category: "gear", weight: 4, cost: coins(5) },
  { name: "Disguise Kit", category: "gear", weight: 3, cost: coins(25), description: "Cosmetics, hair dye, small props, and a few costumes for creating disguises." },
  // SRD 5.2 tools table (15 GP, 5 lb). toolCategory "other", not
  // artisan/gaming/instrument (#1564).
  { name: "Forgery Kit", category: "gear", weight: 5, cost: coins(15), description: "Papers, parchments, inks, seals, and sealing wax for producing convincing forgeries.", toolCategory: "other" },
  { name: "Book of Lore", category: "gear", weight: 5, cost: coins(25), description: "A book containing knowledge in a particular field." },
  { name: "Parchment Sheet", category: "gear", weight: 0, cost: coins(0, 1, 0) },
  { name: "Knife", category: "gear", weight: 0.5, cost: coins(0, 2, 0) },
  {
    name: "Scimitar",
    category: "weapon",
    weight: 3,
    cost: coins(25),
    weapon: { damageDiceCount: 1, damageDiceFaces: 6, damageType: "slashing", finesse: true, light: true, weaponClass: "martial", weaponRange: "melee" },
  },
  {
    name: "Dart",
    category: "weapon",
    weight: 0.25,
    cost: coins(0, 0, 5),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 4,
      damageType: "piercing",
      finesse: true,
      thrown: true,
      rangeNormal: 20,
      rangeLong: 60,
      weaponClass: "simple",
      weaponRange: "ranged",
    },
  },
  {
    name: "Druidic Focus",
    category: "gear",
    weight: 0,
    cost: coins(1),
    description: "A sprig of mistletoe, a totem, a staff, or a wooden rod used by druids as a spellcasting focus in place of material components.",
  },
  // Values identical in both editions, so untagged rows serve both (Item
  // carries no `edition` column). Deliberately omits SRD 5.2's
  // weapon-mastery properties (Graze/Sap/Nick/Vex/Topple) — unread by this
  // codebase.
  {
    name: "Greatsword",
    category: "weapon",
    weight: 6,
    cost: coins(50),
    weapon: {
      damageDiceCount: 2,
      damageDiceFaces: 6,
      damageType: "slashing",
      heavy: true,
      twoHanded: true,
      weaponClass: "martial",
      weaponRange: "melee",
    },
  },
  {
    name: "Flail",
    category: "weapon",
    weight: 2,
    cost: coins(10),
    weapon: { damageDiceCount: 1, damageDiceFaces: 8, damageType: "bludgeoning", weaponClass: "martial", weaponRange: "melee" },
  },
  {
    name: "Spear",
    category: "weapon",
    weight: 3,
    cost: coins(1),
    weapon: {
      damageDiceCount: 1,
      damageDiceFaces: 6,
      damageType: "piercing",
      thrown: true,
      rangeNormal: 20,
      rangeLong: 60,
      versatileDiceCount: 1,
      versatileDiceFaces: 8,
      weaponClass: "simple",
      weaponRange: "melee",
    },
  },
  {
    name: "Sickle",
    category: "weapon",
    weight: 2,
    cost: coins(1),
    weapon: { damageDiceCount: 1, damageDiceFaces: 4, damageType: "slashing", light: true, weaponClass: "simple", weaponRange: "melee" },
  },
  {
    name: "Studded Leather Armor",
    category: "armor",
    weight: 13,
    cost: coins(45),
    armor: { armorCategory: "light", baseArmorClass: 12, dexModifierApplies: true },
  },
  {
    name: "Chain Shirt",
    category: "armor",
    weight: 20,
    cost: coins(50),
    armor: { armorCategory: "medium", baseArmorClass: 13, dexModifierApplies: true, dexModifierMax: 2 },
  },
  { name: "Quiver", category: "gear", weight: 1, cost: coins(1) },
  // SRD 5.1 "Robes" / SRD 5.2 "Robe" — shared row uses the latter spelling.
  { name: "Robe", category: "gear", weight: 4, cost: coins(1) },
  { name: "Crystal", category: "gear", weight: 1, cost: coins(10), description: "Used by a spellcaster as an arcane focus in place of components." },
  { name: "Orb", category: "gear", weight: 3, cost: coins(20), description: "Used by a spellcaster as an arcane focus in place of components." },
  { name: "Herbalism Kit", category: "gear", weight: 3, cost: coins(5), description: "Used to identify plants and to craft potions of healing and antitoxin.", toolCategory: "other" },
  // lib/srd/tools.ts's TOOLS already lists these; resolveFixedItems resolves
  // against Item ∪ Pack only, never TOOLS, so they need their own Item rows too.
  { name: "Bagpipes", category: "gear", weight: 6, cost: coins(30), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Drum", category: "gear", weight: 3, cost: coins(6), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Dulcimer", category: "gear", weight: 10, cost: coins(25), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Flute", category: "gear", weight: 1, cost: coins(2), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Horn", category: "gear", weight: 2, cost: coins(3), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Lyre", category: "gear", weight: 2, cost: coins(30), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Pan Flute", category: "gear", weight: 2, cost: coins(12), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Shawm", category: "gear", weight: 1, cost: coins(2), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Viol", category: "gear", weight: 1, cost: coins(30), description: "A musical instrument.", toolCategory: "musicalInstrument" },
  { name: "Traveler's Clothes", category: "gear", weight: 4, cost: coins(2) },
  { name: "Common Clothes", category: "gear", weight: 3, cost: coins(0, 5, 0) },
  { name: "Pouch", category: "gear", weight: 1, cost: coins(0, 5, 0), description: "A small drawstring pouch that can hold coins or other small objects." },
  // Already priced in TOOLS (lib/srd/tools.ts) but had no Item row — same
  // two-registry gap as the instruments above.
  { name: "Calligrapher's Supplies", category: "gear", weight: 5, cost: coins(10), description: "Ink, a quill, and fine parchment for producing beautiful lettering.", toolCategory: "artisan" },
  // SRD 5.1 Acolyte — priced like the generic "Book" entry, kept separate
  // from Book of Lore's subject-specific flavor.
  { name: "Prayer Book", category: "gear", weight: 5, cost: coins(25), description: "A book of prayers and devotions used in religious observances." },
  // SRD 5.1/5.2 Adventuring Gear table; weight 0 (uninstrumented by either
  // SRD, matching this catalog's convention).
  { name: "Dice Set", category: "gear", weight: 0, cost: coins(0, 1, 0), description: "A gaming set.", toolCategory: "gamingSet" },
  { name: "Dragonchess Set", category: "gear", weight: 0, cost: coins(1), description: "A gaming set.", toolCategory: "gamingSet" },
  { name: "Playing Card Set", category: "gear", weight: 0, cost: coins(0, 5, 0), description: "A gaming set.", toolCategory: "gamingSet" },
  { name: "Three-Dragon Ante Set", category: "gear", weight: 0, cost: coins(1), description: "A gaming set.", toolCategory: "gamingSet" },
  // SRD 5.1/5.2 tools tables — identical in both editions, one untagged row
  // each. Values mirror lib/srd/tools.ts's TOOLS exactly; a test pins them
  // equal, so keep them in sync.
  { name: "Alchemist's Supplies", category: "gear", weight: 8, cost: coins(50), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Brewer's Supplies", category: "gear", weight: 9, cost: coins(20), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Carpenter's Tools", category: "gear", weight: 6, cost: coins(8), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Cartographer's Tools", category: "gear", weight: 6, cost: coins(15), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Cobbler's Tools", category: "gear", weight: 5, cost: coins(5), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Cook's Utensils", category: "gear", weight: 8, cost: coins(1), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Glassblower's Tools", category: "gear", weight: 5, cost: coins(30), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Jeweler's Tools", category: "gear", weight: 2, cost: coins(25), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Leatherworker's Tools", category: "gear", weight: 5, cost: coins(5), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Mason's Tools", category: "gear", weight: 8, cost: coins(10), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Painter's Supplies", category: "gear", weight: 5, cost: coins(10), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Potter's Tools", category: "gear", weight: 3, cost: coins(10), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Smith's Tools", category: "gear", weight: 8, cost: coins(20), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Tinker's Tools", category: "gear", weight: 10, cost: coins(50), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Weaver's Tools", category: "gear", weight: 5, cost: coins(1), description: "Artisan's tools.", toolCategory: "artisan" },
  { name: "Woodcarver's Tools", category: "gear", weight: 5, cost: coins(1), description: "Artisan's tools.", toolCategory: "artisan" },
  // SRD 5.1 Adventuring Gear (#1570). "Iron Pot" is the SRD's "Pot, iron".
  { name: "Shovel", category: "gear", weight: 5, cost: coins(2) },
  { name: "Iron Pot", category: "gear", weight: 10, cost: coins(2), description: "An iron pot for cooking over a campfire." },
];
