// ── Spell catalog ─────────────────────────────────────────────────────────────
// A curated SRD subset (cantrips–L3) seeded for the spell-catalog picker and
// auto-rolling feature. Structured effect fields (effectKind/effectDiceCount
// etc.) mirror ItemWeaponDetail / ItemConsumableDetail so the frontend can roll
// damage/healing at cast time using the same dice.ts engine.
export type SpellSchoolSeed =
  | "abjuration" | "conjuration" | "divination" | "enchantment"
  | "evocation" | "illusion" | "necromancy" | "transmutation";

export interface CatalogSpell {
  name: string;
  level: number;
  school: SpellSchoolSeed;
  castingTime: string;
  range: string;
  duration: string;
  description: string;
  concentration?: boolean;
  ritual?: boolean;
  classes: string[];          // lowercase class names
  components?: {
    verbal: boolean;
    somatic: boolean;
    material: boolean;
    materialDescription?: string;
  };
  saveEffect?: "half" | "none"; // for save-based damage spells
  effectKind?: "damage" | "heal" | "buff";
  effectDiceCount?: number;
  effectDiceFaces?: number;
  effectModifier?: number;    // flat bonus (e.g. +3 in "3d4+3" for Magic Missile)
  damageType?: string;
  attackType?: "attack" | "save";
  saveAbility?: string;
  upcastDicePerLevel?: number;
  cantripScaling?: boolean;
  // AC-buff effect (#363): target consumed at the AC-assembly seam — "ac" (flat
  // add, Shield of Faith +2), "acUnarmoredBase" (Mage Armor base 13+Dex),
  // "acFloor" (Barkskin floor 16). buffModifier carries N.
  buffTarget?: "ac" | "acUnarmoredBase" | "acFloor";
  buffModifier?: number;
}

export const SPELLS: CatalogSpell[] = [
  // ── Cantrips ──────────────────────────────────────────────────────────────
  {
    name: "Fire Bolt",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "A mote of fire streaks toward a creature. Make a ranged spell attack. On a hit, deal 1d10 fire damage (scales to 2d10 at level 5, 3d10 at level 11, 4d10 at level 17).",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 10,
    damageType: "fire",
    attackType: "attack",
    cantripScaling: true,
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature. It must succeed on a Dexterity saving throw or take 1d8 radiant damage (scales to 2d8 at level 5, 3d8 at 11, 4d8 at 17). No cover bonus.",
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    damageType: "radiant",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "none",
    cantripScaling: true,
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Unleash a string of insults laden with magic. The target must succeed on a Wisdom save or take 1d4 psychic damage and have disadvantage on its next attack roll (scales to 2d4 at level 5, 3d4 at 11, 4d4 at 17).",
    classes: ["bard"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 4,
    damageType: "psychic",
    attackType: "save",
    saveAbility: "wisdom",
    saveEffect: "none",
    cantripScaling: true,
  },
  {
    name: "Toll the Dead",
    level: 0,
    school: "necromancy",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Point at a creature and the sound of a dolorous bell fills the air. It must succeed on a Constitution save or take 1d8 necrotic damage (1d12 if it's missing HP). Scales at level 5/11/17.",
    classes: ["cleric", "wizard"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    damageType: "necrotic",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "none",
    cantripScaling: true,
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 ft",
    duration: "1 minute",
    description: "A spectral, floating hand appears at a point you choose within range. It can manipulate objects, open doors, or stow items, but can't attack or carry more than 10 pounds.",
    classes: ["wizard", "sorcerer", "bard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "10 ft",
    duration: "Up to 1 hour",
    description: "Magical tricks: create a small sensory effect, light or snuff a flame, clean or soil an object, warm or chill food, create a mark, produce a trinket-like item, or activate/cancel a past prestidigitation effect.",
    classes: ["wizard", "sorcerer", "bard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Light",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    duration: "1 hour",
    description: "Touch one object no larger than 10 feet in any dimension. Until the spell ends, it emits bright light in a 20-foot radius and dim light for an additional 20 feet.",
    classes: ["cleric", "bard", "wizard", "sorcerer"],
    components: { verbal: true, somatic: false, material: true, materialDescription: "a firefly or phosphorescent moss" },
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "illusion",
    castingTime: "1 action",
    range: "30 ft",
    duration: "1 minute",
    description: "Create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it or cast this spell again. A creature that uses its action to examine the illusion can determine it is illusory with a successful Investigation check against your spell save DC.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fleece" },
  },
  // ── Level 1 ───────────────────────────────────────────────────────────────
  {
    name: "Magic Missile",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "Three glowing darts of magical force hit automatically (1d4+1 each = 3d4+3 total). At higher levels: +1 dart per slot level above 1st.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 4,
    effectModifier: 3,
    damageType: "force",
    upcastDicePerLevel: 1,   // +1 dart (1d4+1) per level; effectModifier also increases by 1
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    description: "Touch a living creature and restore 1d8 + spellcasting modifier HP. At higher levels: +1d8 per slot level above 1st.",
    classes: ["cleric", "bard", "druid"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "heal",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    upcastDicePerLevel: 1,
  },
  {
    name: "Healing Word",
    level: 1,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Call out words of restoration to restore 1d4 + spellcasting modifier HP to a visible creature within range. At higher levels: +1d4 per slot level above 1st.",
    classes: ["cleric", "bard", "druid"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "heal",
    effectDiceCount: 1,
    effectDiceFaces: 4,
    upcastDicePerLevel: 1,
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "8 hours",
    description: "Touch a willing creature not wearing armor. Until the spell ends, the target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a piece of cured leather" },
    // Non-concentration → seeded as a while-active buff; ends on long rest, on
    // dismiss, or when the wearer dons body armor (true-end equip hook, #363).
    effectKind: "buff",
    buffTarget: "acUnarmoredBase",
    buffModifier: 13,
  },
  {
    name: "Shield of Faith",
    level: 1,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "60 feet",
    duration: "Concentration, up to 10 minutes",
    description: "A shimmering field surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
    concentration: true,
    classes: ["cleric", "paladin"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small parchment with a bit of holy text written on it" },
    // Flat +2 AC — rides the #383 additive `ac` breakdown channel; drops when
    // concentration breaks.
    effectKind: "buff",
    buffTarget: "ac",
    buffModifier: 2,
  },
  {
    name: "Shield",
    level: 1,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "Self",
    duration: "1 round",
    description: "Reaction to an attack hitting you: +5 AC until the start of your next turn (potentially turning the hit into a miss), plus immunity to Magic Missile.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-ft cube)",
    duration: "Instantaneous",
    description: "A wave of thunderous force sweeps out. Each creature in a 15-ft cube must succeed on a Constitution save or take 2d8 thunder damage and be pushed 10 feet. At higher levels: +1d8 per slot level above 1st.",
    classes: ["wizard", "druid", "bard", "sorcerer", "cleric"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 2,
    effectDiceFaces: 8,
    damageType: "thunder",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "none",
    upcastDicePerLevel: 1,
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-ft cone)",
    duration: "Instantaneous",
    description: "A thin sheet of flames shoots from your fingertips. Each creature in a 15-ft cone must make a Dexterity save, taking 3d6 fire damage on a failure, half as much on a success. At higher levels: +1d6 per slot level above 1st.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 10 minutes",
    description: "Sense the presence of magic within 30 feet. You can use your action to see a faint aura around visible magical creatures or objects and learn its school of magic, if any.",
    classes: ["wizard", "cleric", "druid", "bard"],
    components: { verbal: true, somatic: true, material: false },
    concentration: true,
    ritual: true,
  },
  // ── Level 2 ───────────────────────────────────────────────────────────────
  {
    name: "Barkskin",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "You touch a willing creature. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 16, regardless of what kind of armor it is wearing.",
    concentration: true,
    classes: ["druid", "ranger"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a handful of oak bark" },
    // AC floor 16 — applied last at the AC-assembly seam, stacking as a floor
    // over armor/Dex; drops when concentration breaks.
    effectKind: "buff",
    buffTarget: "acFloor",
    buffModifier: 16,
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "Create three rays of fire; make a separate ranged spell attack for each. On a hit, each ray deals 2d6 fire damage (total 6d6 if all hit). At higher levels: +1 ray per slot level above 2nd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 6,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "attack",
    upcastDicePerLevel: 2,   // +1 ray (+2d6) per slot level above 2nd
  },
  {
    name: "Gust of Wind",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-ft line)",
    duration: "Concentration, up to 1 minute",
    description: "A line of strong wind 60 ft long and 10 ft wide blasts from you. Each creature in the line must succeed on a Strength save or be pushed 15 ft away. The wind disperses gas and vapor and extinguishes small flames.",
    classes: ["druid", "ranger", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a legume seed" },
    concentration: true,
    attackType: "save",
    saveAbility: "strength",
  },
  {
    name: "Misty Step",
    level: 2,
    school: "conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    duration: "Instantaneous",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.",
    classes: ["wizard", "sorcerer", "bard"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Shatter",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "A sudden loud ringing noise causes creatures and objects in a 10-ft-radius sphere to take 3d8 thunder damage on a failed Constitution save, half on a success. Inorganic material has disadvantage. At higher levels: +1d8 per slot above 2nd.",
    classes: ["bard", "sorcerer", "wizard", "cleric"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a chip of mica" },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 8,
    damageType: "thunder",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Hold Person",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "Choose a humanoid within range. It must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, it can repeat the save.",
    classes: ["bard", "cleric", "druid", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small straight piece of iron" },
    concentration: true,
    attackType: "save",
    saveAbility: "wisdom",
  },
  // ── Level 3 ───────────────────────────────────────────────────────────────
  {
    name: "Fireball",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "150 ft",
    duration: "Instantaneous",
    description: "A bright streak flashes to a point you choose, then blossoms into an explosion. Each creature in a 20-ft-radius sphere must make a Dexterity save. On failure, 8d6 fire damage; half on success. At higher levels: +1d6 per slot level above 3rd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny ball of bat guano and sulfur" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (100-ft line)",
    duration: "Instantaneous",
    description: "A stroke of lightning blasts out in a 100-ft line. Each creature in the line makes a Dexterity save. On failure, 8d6 lightning damage; half on success. At higher levels: +1d6 per slot level above 3rd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fur and a rod of amber, crystal, or glass" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 6,
    damageType: "lightning",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Counterspell",
    level: 3,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Attempt to interrupt a creature in the process of casting a spell. If the spell is 3rd level or lower, it fails automatically. If it's 4th level or higher, make an ability check (DC = 10 + spell's level).",
    classes: ["wizard", "sorcerer", "bard", "cleric"],
    components: { verbal: false, somatic: true, material: false },
  },
  {
    name: "Mass Healing Word",
    level: 3,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "As you call out words of restoration, up to six creatures you choose within range each regain 1d4 + spellcasting modifier HP. At higher levels: +1d4 per slot level above 3rd.",
    classes: ["cleric", "bard"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "heal",
    effectDiceCount: 1,
    effectDiceFaces: 4,
    upcastDicePerLevel: 1,
  },
  {
    name: "Gaseous Form",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "A willing creature you touch, along with everything it's wearing and carrying, becomes a misty cloud for the duration. It has a flying speed of 10 ft, can pass through small holes, and has resistance to nonmagical damage, but can't attack or cast spells.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of gauze and a wisp of smoke" },
    concentration: true,
  },
  {
    name: "Fly",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 10 minutes",
    description: "A willing creature you touch gains a flying speed of 60 ft for the duration. At higher levels, target one additional creature per slot level above 3rd.",
    classes: ["wizard", "sorcerer", "warlock"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a wing feather from any bird" },
    concentration: true,
  },
  // ── Level 4 ───────────────────────────────────────────────────────────────
  {
    name: "Stoneskin",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "One willing creature you touch gains resistance to nonmagical bludgeoning, piercing, and slashing damage for the duration.",
    classes: ["druid", "ranger", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "diamond dust worth 100 gp, consumed" },
    concentration: true,
  },
  {
    name: "Wall of Fire",
    level: 4,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Concentration, up to 1 minute",
    description: "Create a wall of fire up to 60 ft long, 20 ft high, and 1 ft thick. Each creature within 10 ft of one side takes 5d8 fire damage on a failed Dexterity save, half on a success. At higher levels: +1d8 per slot above 4th.",
    classes: ["druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small piece of phosphorus" },
    effectKind: "damage",
    effectDiceCount: 5,
    effectDiceFaces: 8,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    concentration: true,
    upcastDicePerLevel: 1,
  },
  // ── Level 5 ───────────────────────────────────────────────────────────────
  {
    name: "Wall of Stone",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Concentration, up to 10 minutes",
    description: "A nonmagical wall of solid stone springs into existence — up to ten 10-ft-by-10-ft panels, each 6 inches thick. If you concentrate for the full duration, the wall becomes permanent.",
    classes: ["druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small block of granite" },
    concentration: true,
  },
  {
    name: "Cone of Cold",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-ft cone)",
    duration: "Instantaneous",
    description: "A blast of cold air erupts from your hands. Each creature in a 60-ft cone takes 8d8 cold damage on a failed Constitution save, half on a success. At higher levels: +1d8 per slot above 5th.",
    classes: ["sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small crystal or glass cone" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 8,
    damageType: "cold",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
];
