// ── Spell catalog ─────────────────────────────────────────────────────────────
// A curated SRD subset (cantrips–L3) seeded for the spell-catalog picker and
// auto-rolling feature. Structured effect fields (effectKind/effectDiceCount
// etc.) mirror ItemWeaponDetail / ItemConsumableDetail so the frontend can roll
// damage/healing at cast time using the same dice.ts engine.
export type SpellSchoolSeed =
  | "abjuration" | "conjuration" | "divination" | "enchantment"
  | "evocation" | "illusion" | "necromancy" | "transmutation";

export interface CatalogSpell {
  name: string;
  level: number;
  school: SpellSchoolSeed;
  castingTime: string;
  range: string;
  duration: string;
  description: string;
  concentration?: boolean;
  ritual?: boolean;
  classes: string[];          // lowercase class names
  components?: {
    verbal: boolean;
    somatic: boolean;
    material: boolean;
    materialDescription?: string;
  };
  saveEffect?: "half" | "none"; // for save-based damage spells
  effectKind?: "damage" | "heal" | "buff";
  effectDiceCount?: number;
  effectDiceFaces?: number;
  effectModifier?: number;    // flat bonus (e.g. +3 in "3d4+3" for Magic Missile)
  damageType?: string;
  attackType?: "attack" | "save";
  saveAbility?: string;
  upcastDicePerLevel?: number;
  cantripScaling?: boolean;
  // AC-buff effect (#363): target consumed at the AC-assembly seam. buffModifier
  // is the ABSOLUTE value the target reads, not a delta — a flat add for "ac"
  // (Shield of Faith 2), the full unarmored base for "acUnarmoredBase" (Mage Armor
  // 13, not 3), the floor for "acFloor" (Barkskin 17).
  buffTarget?: "ac" | "acUnarmoredBase" | "acFloor";
  buffModifier?: number;
}

// SRD 5.2 (2024) renamed the proper-noun spells (#1132). Each entry renames the
// catalog row in place at seed time (applySpellRenames, before the upsert loop),
// preserving its id so SubclassGrantedSpell FKs / InventoryCapability.spellId
// provenance survive. `to` MUST be a live SPELLS name; `from` MUST NOT be (the
// seed-data shape test enforces both).
export interface SpellRename {
  from: string;
  to: string;
}

export const SPELL_RENAMES: SpellRename[] = [
  { from: "Tasha's Hideous Laughter", to: "Hideous Laughter" },
];

export const SPELLS: CatalogSpell[] = [
  // ── Cantrips ──────────────────────────────────────────────────────────────
  {
    name: "Fire Bolt",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "A mote of fire streaks toward a creature. Make a ranged spell attack. On a hit, deal 1d10 fire damage (scales to 2d10 at level 5, 3d10 at level 11, 4d10 at level 17).",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 10,
    damageType: "fire",
    attackType: "attack",
    cantripScaling: true,
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature. It must succeed on a Dexterity saving throw or take 1d8 radiant damage (scales to 2d8 at level 5, 3d8 at 11, 4d8 at 17). The target gains no benefit from cover for this save.",
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    damageType: "radiant",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "none",
    cantripScaling: true,
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Unleash a string of insults laden with magic. The target must succeed on a Wisdom save or take 1d6 psychic damage and have disadvantage on its next attack roll before the end of its next turn (scales to 2d6 at level 5, 3d6 at 11, 4d6 at 17).",
    classes: ["bard"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 6,
    damageType: "psychic",
    attackType: "save",
    saveAbility: "wisdom",
    saveEffect: "none",
    cantripScaling: true,
  },
  // Toll the Dead removed (#1132): no SRD 5.2 version exists, so it can't satisfy
  // the class-list criterion. Learned copies keep working via their snapshots.
  {
    name: "Mage Hand",
    level: 0,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 ft",
    duration: "1 minute",
    description: "A spectral, floating hand appears at a point you choose within range. It can manipulate objects, open doors, or stow items, but can't attack or carry more than 10 pounds.",
    classes: ["wizard", "sorcerer", "bard", "warlock"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "10 ft",
    duration: "1 hour",
    description: "Magical tricks: create a small sensory effect, light or snuff a flame, clean or soil an object, warm or chill food, create a mark, produce a trinket-like item, or activate/cancel a past prestidigitation effect.",
    classes: ["wizard", "sorcerer", "bard", "warlock"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Light",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    duration: "1 hour",
    description: "Touch one object no larger than 10 feet in any dimension. Until the spell ends, it emits bright light in a 20-foot radius and dim light for an additional 20 feet.",
    classes: ["cleric", "bard", "wizard", "sorcerer"],
    components: { verbal: true, somatic: false, material: true, materialDescription: "a firefly or phosphorescent moss" },
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "illusion",
    castingTime: "1 action",
    range: "30 ft",
    duration: "1 minute",
    description: "Create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it or cast this spell again. A creature that uses its action to examine the illusion can determine it is illusory with a successful Investigation check against your spell save DC.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    // SRD 5.2: components are S, M only — no verbal (fixes a pre-existing seed bug).
    components: { verbal: false, somatic: true, material: true, materialDescription: "a bit of fleece" },
  },
  // #1131: SRD 5.2 (2024) cantrips added so every caster's creation picker has
  // real choice. Eldritch Blast is the issue's acceptance-criterion warlock spell.
  {
    name: "Eldritch Blast",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "You hurl a beam of crackling energy toward a creature or object within range. Make a ranged spell attack. On a hit, the target takes 1d10 Force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three at 11th, and four at 17th. You can aim the beams at the same or different targets, making a separate attack roll for each.",
    classes: ["warlock"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 10,
    damageType: "force",
    attackType: "attack",
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    description: "Channeling the chill of the grave, make a melee spell attack against a creature within reach. On a hit, the target takes 1d10 Necrotic damage, and it can't regain Hit Points until the start of your next turn (scales to 2d10 at level 5, 3d10 at 11, 4d10 at 17).",
    classes: ["sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 10,
    damageType: "necrotic",
    attackType: "attack",
    cantripScaling: true,
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "necromancy",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Instantaneous",
    description: "You spray toxic mist at a creature within range. Make a ranged spell attack. On a hit, the target takes 1d12 Poison damage (scales to 2d12 at level 5, 3d12 at 11, 4d12 at 17).",
    classes: ["druid", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 12,
    damageType: "poison",
    attackType: "attack",
    cantripScaling: true,
  },
  {
    name: "Produce Flame",
    level: 0,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 ft",
    duration: "10 minutes",
    description: "A flickering flame appears in your hand, shedding bright light in a 10-foot radius and dim light for an additional 10 feet, and lasts for the duration. You can also hurl the flame at a creature within range as part of casting the spell (ending the light): make a ranged spell attack, and on a hit the target takes 1d8 Fire damage (scales to 2d8 at level 5, 3d8 at 11, 4d8 at 17).",
    classes: ["druid"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    damageType: "fire",
    attackType: "attack",
    cantripScaling: true,
  },
  {
    name: "Druidcraft",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Instantaneous",
    description: "Whispering to the spirits of nature, you create one of the following effects within range: a tiny, harmless sensory effect that predicts the weather for the next 24 hours; instantly make a flower blossom, a seed pod open, or a leaf bud bloom; create an instantaneous, harmless sensory effect (falling leaves, a puff of wind, a small animal's sound, or a faint odor); or instantly light or snuff out a candle, torch, or small campfire.",
    classes: ["druid"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Guidance",
    level: 0,
    school: "divination",
    castingTime: "1 action",
    range: "Touch",
    duration: "Up to 1 minute",
    description: "You touch a willing creature and choose a skill. Until the spell ends, the creature adds 1d4 to any ability check it makes using that skill. Requires Concentration.",
    concentration: true,
    classes: ["cleric", "druid"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Up to 1 minute",
    description: "You manifest a minor wonder within range: your voice booms up to three times as loud for 1 minute; you cause flames to flicker, brighten, dim, or change color; you cause harmless tremors in the ground; you create an instantaneous sound (a crack of thunder, a raven's caw, ominous whispers); you instantly cause an unlocked door or window to fly open or slam shut; or you alter the appearance of your eyes for 1 minute. You can have up to three of these effects active at a time.",
    classes: ["cleric"],
    components: { verbal: true, somatic: false, material: false },
  },
  // ── Level 1 ───────────────────────────────────────────────────────────────
  {
    name: "Magic Missile",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "Three glowing darts of magical force hit automatically (1d4+1 each = 3d4+3 total). At higher levels: +1 dart per slot level above 1st.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 4,
    effectModifier: 3,
    damageType: "force",
    upcastDicePerLevel: 1,   // +1 dart (1d4+1) per level; effectModifier also increases by 1
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    description: "Touch a creature and restore 2d8 + spellcasting modifier HP. At higher levels: +2d8 per slot level above 1st.",
    classes: ["cleric", "bard", "druid", "paladin", "ranger"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "heal",
    effectDiceCount: 2,
    effectDiceFaces: 8,
    upcastDicePerLevel: 2,
  },
  {
    name: "Healing Word",
    level: 1,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Call out words of restoration to restore 2d4 + spellcasting modifier HP to a visible creature within range. At higher levels: +2d4 per slot level above 1st.",
    classes: ["cleric", "bard", "druid"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "heal",
    effectDiceCount: 2,
    effectDiceFaces: 4,
    upcastDicePerLevel: 2,
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "8 hours",
    description: "Touch a willing creature not wearing armor. Until the spell ends, the target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a piece of cured leather" },
    // Non-concentration → seeded as a while-active buff; ends on long rest, on
    // dismiss, or when the wearer dons body armor (true-end equip hook, #363).
    effectKind: "buff",
    buffTarget: "acUnarmoredBase",
    buffModifier: 13,
  },
  {
    name: "Shield of Faith",
    level: 1,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "60 feet",
    duration: "Concentration, up to 10 minutes",
    description: "A shimmering field surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
    concentration: true,
    classes: ["cleric", "paladin"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small parchment with a bit of holy text written on it" },
    // Flat +2 AC — rides the #383 additive `ac` breakdown channel; drops when
    // concentration breaks.
    effectKind: "buff",
    buffTarget: "ac",
    buffModifier: 2,
  },
  {
    name: "Shield",
    level: 1,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "Self",
    duration: "1 round",
    description: "Reaction to an attack hitting you: +5 AC until the start of your next turn (potentially turning the hit into a miss), plus immunity to Magic Missile.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-ft cube)",
    duration: "Instantaneous",
    description: "A wave of thunderous force sweeps out. Each creature in a 15-ft cube must succeed on a Constitution save or take 2d8 thunder damage and be pushed 10 feet. At higher levels: +1d8 per slot level above 1st.",
    classes: ["wizard", "druid", "bard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 2,
    effectDiceFaces: 8,
    damageType: "thunder",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "none",
    upcastDicePerLevel: 1,
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-ft cone)",
    duration: "Instantaneous",
    description: "A thin sheet of flames shoots from your fingertips. Each creature in a 15-ft cone must make a Dexterity save, taking 3d6 fire damage on a failure, half as much on a success. At higher levels: +1d6 per slot level above 1st.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 10 minutes",
    description: "Sense the presence of magic within 30 feet. You can use your action to see a faint aura around visible magical creatures or objects and learn its school of magic, if any.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
    concentration: true,
    ritual: true,
  },
  // Granted-list additions (#912): referenced by official oath/domain/patron
  // spell lists (#913). Utility unless the spell rolls single-type damage/heal.
  {
    name: "Bane",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "Up to three creatures you can see must make a Charisma save. On a failure, a target subtracts 1d4 from every attack roll and saving throw it makes until the spell ends.",
    concentration: true,
    classes: ["bard", "cleric", "warlock"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a drop of blood" },
  },
  {
    name: "Bless",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "Up to three creatures of your choice add 1d4 to every attack roll and saving throw they make until the spell ends. At higher levels: +1 target per slot level above 1st.",
    concentration: true,
    classes: ["cleric", "paladin"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a sprinkling of holy water" },
  },
  {
    name: "Charm Person",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 ft",
    duration: "1 hour",
    description: "One humanoid you can see must succeed on a Wisdom save or be charmed by you until the spell ends or you or your companions harm it. At higher levels: +1 target per slot level above 1st.",
    classes: ["bard", "druid", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Command",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Speak a one-word command to a creature you can see. It must succeed on a Wisdom save or follow the command on its next turn. Typical commands: Approach, Drop, Flee, Grovel, or Halt. At higher levels: +1 target per slot level above 1st.",
    classes: ["bard", "cleric", "paladin"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Disguise Self",
    level: 1,
    school: "illusion",
    castingTime: "1 action",
    range: "Self",
    duration: "1 hour",
    description: "You make yourself — including clothing, armor, weapons, and other belongings — look different until the spell ends. A creature can use its action to inspect you and discern the illusion with an Investigation check against your spell save DC.",
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Dissonant Whispers",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "You whisper a discordant melody only one creature can hear. It must make a Wisdom save, taking 3d6 psychic damage on a failure (half as much on a success) and, on a failure, immediately using its reaction to move away from you. At higher levels: +1d6 per slot level above 1st.",
    classes: ["bard"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 6,
    damageType: "psychic",
    attackType: "save",
    saveAbility: "wisdom",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Ensnaring Strike",
    level: 1,
    school: "conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    duration: "Concentration, up to 1 minute",
    description: "The next time you hit a creature with a weapon attack before the spell ends, thorny vines erupt. The target must succeed on a Strength save or be restrained, taking 1d6 piercing damage at the start of each of its turns while restrained. At higher levels: +1d6 per slot level above 1st.",
    concentration: true,
    classes: ["ranger"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "Each object and creature in a 20-ft cube is outlined in light unless it succeeds on a Dexterity save. Attack rolls against an affected creature or object have advantage, and it can't benefit from being invisible.",
    concentration: true,
    classes: ["bard", "druid"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Hunter's Mark",
    level: 1,
    school: "divination",
    castingTime: "1 bonus action",
    range: "90 ft",
    duration: "Concentration, up to 1 hour",
    description: "You magically mark a creature as your quarry. Until the spell ends, you deal an extra 1d6 Force damage to it whenever you hit it with an attack roll, and you have advantage on Perception and Survival checks to find it. At higher levels: the base 1-hour duration increases with slot level.",
    concentration: true,
    classes: ["ranger"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Protection from Evil and Good",
    level: 1,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 10 minutes",
    description: "Until the spell ends, one willing creature you touch is protected against aberrations, celestials, elementals, fey, fiends, and undead: those creatures have disadvantage on attacks against the target, which also can't be charmed, frightened, or possessed by them.",
    concentration: true,
    classes: ["cleric", "druid", "paladin", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "Holy Water or powdered silver and iron, which the spell consumes" },
  },
  {
    name: "Sanctuary",
    level: 1,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "30 ft",
    duration: "1 minute",
    description: "You ward a creature within range. Any creature that targets the warded creature with an attack or harmful spell must first make a Wisdom save or choose a new target or lose the attack/spell.",
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small silver mirror" },
  },
  {
    name: "Sleep",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "Each creature of your choice in a 5-ft-radius sphere within range must succeed on a Wisdom save or have the Incapacitated condition until the end of its next turn, when it repeats the save. On a second failed save the target falls Unconscious for the duration; a creature's effect ends early if it takes damage or someone uses an action to shake it awake. At higher levels: the radius increases by 5 feet per slot level above 1st.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of fine sand, rose petals, or a cricket" },
  },
  {
    name: "Speak with Animals",
    level: 1,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    duration: "10 minutes",
    description: "You gain the ability to comprehend and verbally communicate with beasts for the duration.",
    ritual: true,
    classes: ["bard", "druid", "ranger"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Hideous Laughter",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "A creature you can see must succeed on a Wisdom save or have the Prone and Incapacitated conditions for the duration, overcome with laughter. It repeats the save at the end of each of its turns (with advantage if it took damage since its last turn). At higher levels: +1 target per slot level above 1st.",
    concentration: true,
    classes: ["bard", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny tart and a feather" },
  },
  // ── Level 2 ───────────────────────────────────────────────────────────────
  {
    name: "Barkskin",
    level: 2,
    school: "transmutation",
    castingTime: "1 bonus action",
    range: "Touch",
    duration: "1 hour",
    description: "You touch a willing creature. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 17, regardless of what kind of armor it is wearing.",
    classes: ["druid", "ranger"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a handful of oak bark" },
    // SRD 5.2: floor 17, non-concentration (while-active, ends on long rest /
    // dismiss). Applied last at the AC-assembly seam, stacking as a floor over
    // armor/Dex.
    effectKind: "buff",
    buffTarget: "acFloor",
    buffModifier: 17,
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "Create three rays of fire; make a separate ranged spell attack for each. On a hit, each ray deals 2d6 fire damage (total 6d6 if all hit). At higher levels: +1 ray per slot level above 2nd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 6,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "attack",
    upcastDicePerLevel: 2,   // +1 ray (+2d6) per slot level above 2nd
  },
  {
    name: "Gust of Wind",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-ft line)",
    duration: "Concentration, up to 1 minute",
    description: "A line of strong wind 60 ft long and 10 ft wide blasts from you. Each creature in the line must succeed on a Strength save or be pushed 15 ft away. The wind disperses gas and vapor and extinguishes small flames.",
    classes: ["druid", "ranger", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a legume seed" },
    concentration: true,
    attackType: "save",
    saveAbility: "strength",
  },
  {
    name: "Misty Step",
    level: 2,
    school: "conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    duration: "Instantaneous",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.",
    classes: ["wizard", "sorcerer", "warlock"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Shatter",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "A sudden loud ringing noise causes creatures and objects in a 10-ft-radius sphere to take 3d8 thunder damage on a failed Constitution save, half on a success. Inorganic material has disadvantage. At higher levels: +1d8 per slot above 2nd.",
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a chip of mica" },
    effectKind: "damage",
    effectDiceCount: 3,
    effectDiceFaces: 8,
    damageType: "thunder",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Hold Person",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "Choose a humanoid within range. It must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, it can repeat the save.",
    classes: ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small straight piece of iron" },
    concentration: true,
    attackType: "save",
    saveAbility: "wisdom",
  },
  // Granted-list additions (#912/#913).
  {
    name: "Blindness/Deafness",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "1 minute",
    description: "One creature you can see must succeed on a Constitution save or be blinded or deafened (your choice) for the duration. It repeats the save at the end of each of its turns. At higher levels: +1 target per slot level above 2nd.",
    classes: ["bard", "cleric", "sorcerer", "wizard"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Calm Emotions",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "Each humanoid in a 20-ft radius must make a Charisma save. On a failure, you can suppress any charmed or frightened condition, or make it indifferent about creatures of your choice that it is hostile toward.",
    concentration: true,
    classes: ["bard", "cleric"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Detect Thoughts",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 1 minute",
    description: "You can read the surface thoughts of a creature within 30 ft. You can probe deeper with a Wisdom save; on a failure you learn its reasoning and deepest thoughts, on a success the spell ends.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a copper piece" },
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "Touch",
    duration: "Instantaneous",
    description: "You touch a creature and end one disease or one condition afflicting it: blinded, deafened, paralyzed, or poisoned.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Mirror Image",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "Self",
    duration: "1 minute",
    description: "Three illusory duplicates of yourself appear in your space. Each time a creature targets you with an attack, roll to see whether it targets a duplicate (destroyed on a hit) instead.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Moonbeam",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Concentration, up to 1 minute",
    description: "A silvery beam fills a 5-ft-radius, 40-ft-high cylinder. A creature that enters the beam or starts its turn there makes a Constitution save, taking 2d10 radiant damage on a failure (half on a success). You can move the beam 60 ft as an action. At higher levels: +1d10 per slot level above 2nd.",
    concentration: true,
    classes: ["druid"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "several seeds of any moonseed plant and a piece of opalescent feldspar" },
    effectKind: "damage",
    effectDiceCount: 2,
    effectDiceFaces: 10,
    damageType: "radiant",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Pass without Trace",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 1 hour",
    description: "A veil of shadows and silence radiates from you, masking you and your companions. Each creature within 30 ft gains a +10 bonus to Stealth checks and can't be tracked except by magical means for the duration.",
    concentration: true,
    classes: ["druid", "ranger"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "ashes from a burned leaf of mistletoe and a sprig of spruce" },
  },
  {
    name: "Phantasmal Force",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "You craft an illusion in the mind of a creature that fails an Intelligence save. It rationalizes the illusion as real; if the illusion can cause harm, it deals 2d8 psychic damage each turn the target believes it real.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fleece" },
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "You create a floating spectral weapon. As a bonus action you can move it and make a melee spell attack, dealing 1d8 + your spellcasting modifier force damage on a hit. At higher levels: +1d8 per slot level above 2nd.",
    concentration: true,
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "damage",
    effectDiceCount: 1,
    effectDiceFaces: 8,
    damageType: "force",
    attackType: "attack",
    upcastDicePerLevel: 1,
  },
  {
    name: "Zone of Truth",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "10 minutes",
    description: "You create a 15-ft-radius zone. A creature that enters or starts its turn there must make a Charisma save; on a failure it can't speak a deliberate lie while in the zone (it can still be evasive).",
    classes: ["bard", "cleric", "paladin"],
    components: { verbal: true, somatic: true, material: false },
  },
  // ── Level 3 ───────────────────────────────────────────────────────────────
  {
    name: "Fireball",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "150 ft",
    duration: "Instantaneous",
    description: "A bright streak flashes to a point you choose, then blossoms into an explosion. Each creature in a 20-ft-radius sphere must make a Dexterity save. On failure, 8d6 fire damage; half on success. At higher levels: +1d6 per slot level above 3rd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny ball of bat guano and sulfur" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 6,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (100-ft line)",
    duration: "Instantaneous",
    description: "A stroke of lightning blasts out in a 100-ft line. Each creature in the line makes a Dexterity save. On failure, 8d6 lightning damage; half on success. At higher levels: +1d6 per slot level above 3rd.",
    classes: ["wizard", "sorcerer"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fur and a rod of amber, crystal, or glass" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 6,
    damageType: "lightning",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  {
    name: "Counterspell",
    level: 3,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "60 ft",
    duration: "Instantaneous",
    description: "You attempt to interrupt a creature in the process of casting a spell. The target must succeed on a Constitution saving throw (DC 10 + the level of the spell it is casting) or its spell fails and has no effect.",
    classes: ["sorcerer", "warlock", "wizard"],
    components: { verbal: false, somatic: true, material: false },
  },
  {
    name: "Mass Healing Word",
    level: 3,
    school: "abjuration",
    castingTime: "1 bonus action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "As you call out words of restoration, up to six creatures you choose within range each regain 2d4 + spellcasting modifier HP. At higher levels: +1d4 per slot level above 3rd.",
    classes: ["cleric", "bard"],
    components: { verbal: true, somatic: false, material: false },
    effectKind: "heal",
    effectDiceCount: 2,
    effectDiceFaces: 4,
    upcastDicePerLevel: 1,
  },
  {
    name: "Gaseous Form",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "A willing creature you touch, along with everything it's wearing and carrying, becomes a misty cloud for the duration. It has a flying speed of 10 ft, can pass through small holes, and has resistance to nonmagical damage, but can't attack or cast spells.",
    classes: ["wizard", "sorcerer", "warlock"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of gauze and a wisp of smoke" },
    concentration: true,
  },
  {
    name: "Fly",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 10 minutes",
    description: "A willing creature you touch gains a flying speed of 60 ft for the duration. At higher levels, target one additional creature per slot level above 3rd.",
    classes: ["wizard", "sorcerer", "warlock"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a wing feather from any bird" },
    concentration: true,
  },
  // Granted-list additions (#912/#913).
  {
    name: "Beacon of Hope",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "Any number of creatures in range gain advantage on Wisdom saves and death saving throws, and regain the maximum number of hit points possible from any healing, for the duration.",
    concentration: true,
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Blink",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self",
    duration: "1 minute",
    description: "At the end of each of your turns, roll a d6. On a 4-6, you vanish to the Ethereal Plane until the start of your next turn, then reappear in an unoccupied space you can see within 10 ft.",
    classes: ["sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Clairvoyance",
    level: 3,
    school: "divination",
    castingTime: "10 minutes",
    range: "1 mile",
    duration: "Concentration, up to 10 minutes",
    description: "You create an invisible sensor within range in a location familiar to you or an obvious one. You can choose to see or hear through it, switching as an action.",
    concentration: true,
    classes: ["bard", "cleric", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a focus worth at least 100 gp (a jeweled horn for hearing or a glass eye for seeing)" },
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Instantaneous",
    description: "Choose one creature, object, or magical effect. Any spell of 3rd level or lower on it ends. For a higher-level spell, make an ability check using your spellcasting ability (DC 10 + the spell's level). At higher levels: automatically end spells of the slot level or lower.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Haste",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "A willing creature's speed doubles, it gains +2 AC, advantage on Dexterity saves, and an additional action each turn (Attack one weapon attack, Dash, Disengage, Hide, or Use an Object). When the spell ends, the target can't move or act until after its next turn.",
    concentration: true,
    classes: ["sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a shaving of licorice root" },
  },
  {
    name: "Plant Growth",
    level: 3,
    school: "transmutation",
    castingTime: "1 action or 8 hours",
    range: "150 ft",
    duration: "Instantaneous",
    description: "Overgrow: plants in a 100-ft radius become difficult terrain, quartering movement. Or Enrich (8-hour cast): plants in a half-mile radius are enriched for one year.",
    classes: ["bard", "druid", "ranger"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Protection from Energy",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.",
    concentration: true,
    classes: ["cleric", "druid", "ranger", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Revivify",
    level: 3,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    description: "You touch a creature that has died within the last minute. It returns to life with 1 hit point. This spell can't return a creature that has died of old age, nor restore missing body parts.",
    classes: ["cleric", "druid", "paladin", "ranger"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "diamonds worth 300 gp, consumed" },
  },
  {
    name: "Sending",
    level: 3,
    school: "divination",
    castingTime: "1 action",
    range: "Unlimited",
    duration: "Instantaneous",
    description: "You send a short message of 25 words or less to a creature you are familiar with. It hears the message in its mind, recognizes you, and can reply in kind immediately.",
    classes: ["bard", "cleric", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a short piece of fine copper wire" },
  },
  {
    name: "Stinking Cloud",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "90 ft",
    duration: "Concentration, up to 1 minute",
    description: "A 20-ft-radius sphere of yellow, nauseating gas forms. Each creature that starts its turn there must succeed on a Constitution save or lose its action that turn, retching. The cloud spreads around corners and heavily obscures the area.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a rotten egg or several skunk cabbage leaves" },
  },
  // ── Level 4 ───────────────────────────────────────────────────────────────
  {
    name: "Stoneskin",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    description: "One willing creature you touch gains resistance to nonmagical bludgeoning, piercing, and slashing damage for the duration.",
    classes: ["druid", "ranger", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "diamond dust worth 100 gp, consumed" },
    concentration: true,
  },
  {
    name: "Wall of Fire",
    level: 4,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Concentration, up to 1 minute",
    description: "Create a wall of fire up to 60 ft long, 20 ft high, and 1 ft thick. Each creature within 10 ft of one side takes 5d8 fire damage on a failed Dexterity save, half on a success. At higher levels: +1d8 per slot above 4th.",
    classes: ["druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small piece of phosphorus" },
    effectKind: "damage",
    effectDiceCount: 5,
    effectDiceFaces: 8,
    damageType: "fire",
    attackType: "save",
    saveAbility: "dexterity",
    saveEffect: "half",
    concentration: true,
    upcastDicePerLevel: 1,
  },
  // Granted-list additions (#912/#913).
  {
    name: "Banishment",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "One creature you can see must succeed on a Charisma save or be banished to a harmless demiplane (or, if native to another plane, back to its home plane) for the duration. At higher levels: +1 target per slot level above 4th.",
    concentration: true,
    classes: ["cleric", "paladin", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "an item distasteful to the target" },
  },
  {
    name: "Death Ward",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "8 hours",
    description: "The first time the warded creature would drop to 0 hit points as a result of taking damage, it instead drops to 1 hit point, and the spell ends. If it would be killed outright, the effect is negated and the spell ends.",
    classes: ["cleric", "paladin"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Dimension Door",
    level: 4,
    school: "conjuration",
    castingTime: "1 action",
    range: "500 ft",
    duration: "Instantaneous",
    description: "You teleport yourself (and one willing creature within 5 ft) to a spot you can see, visualize, or describe by distance and direction, up to 500 ft away.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Dominate Beast",
    level: 4,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "A beast you can see must succeed on a Wisdom save or be charmed and controlled by you for the duration. You issue commands telepathically; the target repeats the save each time it takes damage. At higher levels: duration increases with slot level.",
    concentration: true,
    classes: ["druid", "sorcerer"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Evard's Black Tentacles",
    level: 4,
    school: "conjuration",
    castingTime: "1 action",
    range: "90 ft",
    duration: "Concentration, up to 1 minute",
    description: "Writhing tentacles fill a 20-ft square, which becomes difficult terrain. A creature there must succeed on a Dexterity save or be restrained, taking 3d6 bludgeoning damage at the start of each of its turns while restrained.",
    concentration: true,
    classes: ["wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a piece of tentacle from a giant octopus or giant squid" },
  },
  {
    name: "Fire Shield",
    level: 4,
    school: "evocation",
    castingTime: "1 action",
    range: "Self",
    duration: "10 minutes",
    description: "A shield of flames (or frost) wreathes you, shedding light and granting resistance to cold (or fire) damage. A creature within 5 ft that hits you with a melee attack takes 2d8 fire (or cold) damage.",
    classes: ["wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of phosphorus or a firefly" },
  },
  {
    name: "Freedom of Movement",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "1 hour",
    description: "For the duration, the creature you touch is unaffected by difficult terrain, and spells and effects can't reduce its speed or restrain/paralyze it. It can spend 5 ft of movement to escape nonmagical restraints or grapples.",
    classes: ["bard", "cleric", "druid", "ranger"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a leather strap bound around the arm or a similar appendage" },
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "illusion",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 minute",
    description: "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Guardian of Faith",
    level: 4,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 ft",
    duration: "8 hours",
    description: "A Large spectral guardian appears in an unoccupied space you can see. A hostile creature that moves within 10 ft of it for the first time on a turn must succeed on a Dexterity save or take 20 radiant damage (half on a success). The guardian fades after dealing 60 total damage.",
    classes: ["cleric"],
    components: { verbal: true, somatic: false, material: false },
  },
  {
    name: "Ice Storm",
    level: 4,
    school: "evocation",
    castingTime: "1 action",
    range: "300 ft",
    duration: "Instantaneous",
    description: "Hail pounds a 20-ft-radius, 40-ft-high cylinder. Each creature there makes a Dexterity save, taking 2d8 bludgeoning + 4d6 cold damage on a failure (half on a success). The ground there becomes difficult terrain until the end of your next turn. At higher levels: +1d8 bludgeoning per slot level above 4th.",
    classes: ["druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of dust and a few drops of water" },
  },
  {
    name: "Polymorph",
    level: 4,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 hour",
    description: "A creature you can see transforms — an unwilling one must fail a Wisdom save — into a new beast form whose CR is no higher than its level or CR. It retains its alignment and personality, gains the beast's stats and HP, and reverts when the form drops to 0 HP.",
    concentration: true,
    classes: ["bard", "druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a caterpillar cocoon" },
  },
  // ── Level 5 ───────────────────────────────────────────────────────────────
  {
    name: "Wall of Stone",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "120 ft",
    duration: "Concentration, up to 10 minutes",
    description: "A nonmagical wall of solid stone springs into existence — up to ten 10-ft-by-10-ft panels, each 6 inches thick. If you concentrate for the full duration, the wall becomes permanent.",
    classes: ["druid", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small block of granite" },
    concentration: true,
  },
  {
    name: "Cone of Cold",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-ft cone)",
    duration: "Instantaneous",
    description: "A blast of cold air erupts from your hands. Each creature in a 60-ft cone takes 8d8 cold damage on a failed Constitution save, half on a success. At higher levels: +1d8 per slot above 5th.",
    classes: ["sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small crystal or glass cone" },
    effectKind: "damage",
    effectDiceCount: 8,
    effectDiceFaces: 8,
    damageType: "cold",
    attackType: "save",
    saveAbility: "constitution",
    saveEffect: "half",
    upcastDicePerLevel: 1,
  },
  // Granted-list additions (#912/#913).
  {
    name: "Commune",
    level: 5,
    school: "divination",
    castingTime: "1 minute",
    range: "Self",
    duration: "1 minute",
    description: "You contact your deity and ask up to three questions that can be answered yes or no. You receive a correct answer for each, though the deity may respond \"unclear\" for something beyond its knowledge.",
    ritual: true,
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "incense and a vial of holy or unholy water" },
  },
  {
    name: "Commune with Nature",
    level: 5,
    school: "divination",
    castingTime: "1 minute",
    range: "Self",
    duration: "Instantaneous",
    description: "You become attuned to nature and gain knowledge of the surrounding territory (up to 3 miles outdoors, 300 ft underground): terrain, bodies of water, prevalent creatures, powerful fey or undead, and the like.",
    ritual: true,
    classes: ["druid", "ranger"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Dominate Person",
    level: 5,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 1 minute",
    description: "A humanoid you can see must succeed on a Wisdom save or be charmed and controlled by you for the duration. You issue commands telepathically; the target repeats the save each time it takes damage. At higher levels: duration increases with slot level.",
    concentration: true,
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Flame Strike",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "A vertical column of divine fire roars down in a 10-ft-radius, 40-ft-high cylinder. Each creature there makes a Dexterity save, taking 4d6 fire damage and 4d6 radiant damage on a failure (half on a success). At higher levels: +1d6 (either type) per slot level above 5th.",
    classes: ["cleric", "paladin", "warlock"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "pinch of sulfur" },
  },
  {
    name: "Hallow",
    level: 5,
    school: "evocation",
    castingTime: "24 hours",
    range: "Touch",
    duration: "Until dispelled",
    description: "You imbue a site (up to 60-ft radius) with holy or unholy power: specified creature types can't enter, be charmed, frightened, or possessed there, and you tie one extra effect (such as courage, darkness, or daylight) to the area.",
    classes: ["cleric"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "herbs, oils, and incense worth at least 1,000 gp, consumed" },
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "enchantment",
    castingTime: "1 action",
    range: "90 ft",
    duration: "Concentration, up to 1 minute",
    description: "A creature you can see (not undead) must succeed on a Wisdom save or be paralyzed for the duration, repeating the save at the end of each of its turns. At higher levels: +1 target per slot level above 5th.",
    concentration: true,
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a small, straight piece of iron" },
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Instantaneous",
    description: "Up to six creatures of your choice in a 30-ft-radius sphere each regain 3d8 + your spellcasting modifier hit points. At higher levels: +1d8 per slot level above 5th.",
    classes: ["bard", "cleric", "druid"],
    components: { verbal: true, somatic: true, material: false },
    effectKind: "heal",
    effectDiceCount: 3,
    effectDiceFaces: 8,
    upcastDicePerLevel: 1,
  },
  {
    name: "Modify Memory",
    level: 5,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 ft",
    duration: "Concentration, up to 1 minute",
    description: "A creature you can see must succeed on a Wisdom save or you reshape its memory of an event it experienced within the last 24 hours (lasting up to 10 minutes to describe). You can eliminate, alter, or implant a memory.",
    concentration: true,
    classes: ["bard", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Raise Dead",
    level: 5,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    duration: "Instantaneous",
    description: "You return a creature that has been dead no longer than 10 days to life with 1 hit point. It takes a -4 penalty to attacks, saves, and ability checks that reduces by 1 after each long rest. This spell can't return undead, constructs, or creatures dead of old age, nor restore missing body parts.",
    classes: ["bard", "cleric", "paladin"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a diamond worth at least 500 gp, consumed" },
  },
  {
    name: "Scrying",
    level: 5,
    school: "divination",
    castingTime: "10 minutes",
    range: "Self",
    duration: "Concentration, up to 10 minutes",
    description: "You can see and hear a particular creature you choose that is on the same plane. The target makes a Wisdom save (modified by your familiarity and any physical connection); on a failure, an invisible sensor tracks it for the duration.",
    concentration: true,
    classes: ["bard", "cleric", "druid", "warlock", "wizard"],
    components: { verbal: true, somatic: true, material: true, materialDescription: "a focus worth at least 1,000 gp, such as a crystal ball, silver mirror, or font of holy water" },
  },
  {
    name: "Seeming",
    level: 5,
    school: "illusion",
    castingTime: "1 action",
    range: "30 ft",
    duration: "8 hours",
    description: "This spell lets you change the appearance of any number of creatures you can see within range — their bodies and everything they're wearing or carrying. An unwilling creature can make a Charisma save to be unaffected.",
    classes: ["bard", "sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Telekinesis",
    level: 5,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 ft",
    duration: "Concentration, up to 10 minutes",
    description: "You gain the ability to move or manipulate creatures or objects by thought. As an action you can move a creature (contested by Strength) or a loose object weighing up to 1,000 pounds.",
    concentration: true,
    classes: ["sorcerer", "wizard"],
    components: { verbal: true, somatic: true, material: false },
  },
  {
    name: "Tree Stride",
    level: 5,
    school: "conjuration",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 1 minute",
    description: "You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 ft, using 5 ft of movement. You can make one such transit per turn.",
    concentration: true,
    classes: ["druid", "ranger"],
    components: { verbal: true, somatic: true, material: false },
  },
];
