#!/usr/bin/env bash
#
# worktree.sh — spin up isolated, parallel dev stacks, one per git worktree.
#
# Each worktree gets a port "slot" (1-9). Every port + the Compose project name
# is derived from the slot, so two worktrees never collide and each one gets its
# OWN Postgres volume (migrations in one are invisible to the others). Slot 0 is
# reserved for the main checkout on default ports.
#
#   ./.claude/skills/worktree/worktree.sh create <branch> [--up]   create worktree, assign slot, .env, npm ci
#   ./.claude/skills/worktree/worktree.sh up <branch>              docker compose up -d (build)
#   ./.claude/skills/worktree/worktree.sh down <branch>            docker compose down (keep volumes)
#   ./.claude/skills/worktree/worktree.sh ls                       table of worktrees, slots, URLs, status
#   ./.claude/skills/worktree/worktree.sh rm <branch>              down -v + remove worktree + free slot
#   ./.claude/skills/worktree/worktree.sh prune [--yes]            report/remove artifacts of worktrees already gone
#
set -euo pipefail

# Repo root = three levels up from this script's dir
# (.claude/skills/worktree/). Resolve symlinks for safety.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
WT_DIR="$ROOT/.claude/worktrees"
REGISTRY="$WT_DIR/registry.json"

MAX_SLOT=9

die() { echo "error: $*" >&2; exit 1; }

# Compose project name: lowercase, non-alnum -> '-', collapse repeats, trim.
project_name() {
  local b="$1"
  b="$(printf '%s' "$b" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
  printf 'cs-%s' "$b"
}

ensure_registry() {
  mkdir -p "$WT_DIR"
  [ -f "$REGISTRY" ] || echo '{}' > "$REGISTRY"
}

# Read the slot assigned to a branch, or empty string.
slot_of() {
  ensure_registry
  node -e 'const r=require(process.argv[1]); process.stdout.write(String(r[process.argv[2]]??""))' "$REGISTRY" "$1"
}

# Lowest free slot in 1..MAX_SLOT not present in the registry.
next_free_slot() {
  ensure_registry
  node -e '
    const r=require(process.argv[1]); const max=+process.argv[2];
    const used=new Set(Object.values(r).map(Number));
    for (let i=1;i<=max;i++) if(!used.has(i)){console.log(i);process.exit(0);}
    process.exit(1);
  ' "$REGISTRY" "$MAX_SLOT" || die "no free slots (max $MAX_SLOT worktrees). Run 'rm' on an unused one."
}

registry_set() {
  ensure_registry
  node -e '
    const fs=require("fs"); const f=process.argv[1];
    const r=require(f); r[process.argv[2]]=Number(process.argv[3]);
    fs.writeFileSync(f, JSON.stringify(r,null,2)+"\n");
  ' "$REGISTRY" "$1" "$2"
}

registry_del() {
  ensure_registry
  node -e '
    const fs=require("fs"); const f=process.argv[1];
    const r=require(f); delete r[process.argv[2]];
    fs.writeFileSync(f, JSON.stringify(r,null,2)+"\n");
  ' "$REGISTRY" "$1"
}

# Slot assignment is read-registry -> pick-lowest-free -> write-registry; two
# concurrent creates (e.g. parallel autodev runs) would race that window and
# collide on a slot. mkdir is atomic, so it serves as the mutex — no flock on
# stock macOS.
SLOT_LOCK=""
lock_slots() {
  ensure_registry
  SLOT_LOCK="$WT_DIR/.slot.lock"
  local waited=0
  until mkdir "$SLOT_LOCK" 2>/dev/null; do
    [ "$waited" -ge 30 ] && die "slot lock held for ${waited}s ($SLOT_LOCK); remove it if no create is running"
    sleep 1; waited=$((waited + 1))
  done
  trap 'unlock_slots' EXIT
}
unlock_slots() {
  [ -n "$SLOT_LOCK" ] && rmdir "$SLOT_LOCK" 2>/dev/null
  SLOT_LOCK=""
}

# Echo the port for (slot, base): base + slot*10.
port_for() { echo $(( $2 + $1 * 10 )); }

worktree_path() { echo "$WT_DIR/$1"; }

write_env() {
  local branch="$1" slot="$2" path="$3"
  local proj backend frontend pg pgadmin
  proj="$(project_name "$branch")"
  backend="$(port_for "$slot" 4000)"
  frontend="$(port_for "$slot" 5173)"
  pg="$(port_for "$slot" 5432)"
  pgadmin="$(port_for "$slot" 5050)"
  cat > "$path/.env" <<EOF
# Generated by .claude/skills/worktree/worktree.sh — worktree '$branch', slot $slot.
# Gitignored. Regenerate with: ./.claude/skills/worktree/worktree.sh create $branch
COMPOSE_PROJECT_NAME=$proj
BACKEND_PORT=$backend
FRONTEND_PORT=$frontend
POSTGRES_PORT=$pg
PGADMIN_PORT=$pgadmin
VITE_API_URL=http://localhost:$backend/api
# This worktree's .git is a FILE pointing into the main checkout's .git, so the
# containers need that directory mounted at its own absolute path or git — and
# with it \`fallow --base\` — reports "not a git repository" (#1450).
MAIN_GIT_SRC=$ROOT/.git
MAIN_GIT_DST=$ROOT/.git
EOF
}

print_ports() {
  local branch="$1" slot="$2"
  echo "  slot:     $slot"
  echo "  project:  $(project_name "$branch")"
  echo "  frontend: http://localhost:$(port_for "$slot" 5173)"
  echo "  backend:  http://localhost:$(port_for "$slot" 4000)/api"
  echo "  postgres: localhost:$(port_for "$slot" 5432)"
}

# `git worktree add` checks out tracked files only, and node_modules is
# gitignored — so a fresh worktree has none, and because worktrees live INSIDE
# the repo, Node then resolves upward into the MAIN checkout. That is why host
# tsc/eslint silently check the wrong tree and lefthook's fallow job can't find
# its binary. Installing per worktree is the standard fix (#1452); symlinking
# the main tree's copy is not, because it stops matching the lockfile the moment
# package.json diverges.
#
install_deps() {
  local path="$1"
  [ -d "$path/node_modules" ] && return 0

  echo "Installing dependencies (this is what keeps host tsc/eslint/fallow honest)…"
  ( cd "$path" && npm ci ) || die "npm ci failed in $path"

  # npm ci runs the root `prepare` → `lefthook install`, which bakes an absolute
  # path into `.git/hooks` — a directory every worktree SHARES. Left alone, the
  # shim points into THIS worktree, so deleting it makes the shim fall through
  # to a silent `exit 0` and disables every hook everywhere, including the main
  # checkout (upstream lefthook #1398, open; the baked path is deliberate since
  # 2.0.6). Re-installing from the main checkout points it at a tree that
  # outlives every worktree. LEFTHOOK=0 does NOT prevent this — it gates hook
  # execution, not `lefthook install` (measured).
  ( cd "$ROOT" && npx lefthook install >/dev/null 2>&1 ) || die "could not restore the shared lefthook shim"
  # The Prisma client is gitignored too, so without this the worktree's own tsc
  # can't resolve @/generated/prisma. generate never connects; prisma.config.ts
  # only validates that DATABASE_URL parses.
  ( cd "$path/backend" && DATABASE_URL="postgresql://unused:unused@localhost:5432/unused" npx prisma generate >/dev/null ) \
    || die "prisma generate failed in $path/backend"
}

cmd_create() {
  local branch="${1:-}"; shift || true
  [ -n "$branch" ] || die "usage: worktree.sh create <branch> [base] [--up]"
  # Optional positional base ref to fork from (e.g. "staging") plus the --up flag,
  # in any order. Empty base → fork from the main checkout's HEAD (legacy behavior).
  local base="" do_up=0
  for arg in "$@"; do
    if [ "$arg" = "--up" ]; then do_up=1; else base="$arg"; fi
  done

  local path; path="$(worktree_path "$branch")"
  local slot; slot="$(slot_of "$branch")"

  if [ -d "$path" ]; then
    [ -n "$slot" ] || die "worktree dir exists but no slot recorded; remove $path manually"
    echo "Worktree '$branch' already exists (slot $slot); refreshing .env."
  else
    lock_slots
    slot="$(next_free_slot)"
    # Reuse the branch if it already exists, otherwise create it. A new branch
    # forks from a FRESHLY-FETCHED origin/<base> when a base is given, so a slice
    # never forks off a stale local ref — that stale fork was the cause of the
    # cross-slice merge conflicts in the lib-reorg batch. With no base, fall back
    # to the main checkout's HEAD.
    if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$branch"; then
      git -C "$ROOT" worktree add "$path" "$branch"
    elif [ -n "$base" ]; then
      git -C "$ROOT" fetch --quiet origin "$base"
      git -C "$ROOT" worktree add "$path" -b "$branch" "origin/$base"
    else
      git -C "$ROOT" worktree add "$path" -b "$branch"
    fi
    registry_set "$branch" "$slot"
    unlock_slots
  fi

  write_env "$branch" "$slot" "$path"
  install_deps "$path"
  echo "Worktree '$branch' ready:"
  print_ports "$branch" "$slot"

  if [ "$do_up" = 1 ]; then
    cmd_up "$branch"
  else
    echo "  start it: ./.claude/skills/worktree/worktree.sh up $branch"
  fi
}

cmd_up() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh up <branch>"
  local path; path="$(worktree_path "$branch")"
  [ -d "$path" ] || die "no worktree '$branch' (run: create $branch)"
  echo "Starting '$branch'…"
  ( cd "$path" && docker compose up --build -d )
  print_ports "$branch" "$(slot_of "$branch")"
}

cmd_down() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh down <branch>"
  local path; path="$(worktree_path "$branch")"
  [ -d "$path" ] || die "no worktree '$branch'"
  ( cd "$path" && docker compose down )
}

cmd_rm() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh rm <branch>"
  local path; path="$(worktree_path "$branch")"
  if [ -d "$path" ]; then
    # --profile e2e: compose will NOT remove volumes owned by a service in an
    # inactive profile, so a plain `down -v` left both e2e_*_node_modules behind
    # on every teardown — 74 of them (~16 GB) had accumulated by #1452.
    # --rmi local: drops the project's own built images (<project>-backend/
    # -frontend) while leaving pulled ones (postgres, playwright) alone.
    ( cd "$path" && docker compose --profile e2e down -v --rmi local ) || true
    # A half-torn-down dir (git worktree metadata already pruned) makes
    # `worktree remove` die with "not a working tree" — fall back to removing
    # the dir + pruning so the slot is still freed (the janitor relies on rm
    # never leaving a registry entry behind).
    git -C "$ROOT" worktree remove "$path" --force || { rm -rf "$path"; git -C "$ROOT" worktree prune; }
  fi
  registry_del "$branch"
  echo "Removed worktree '$branch' (containers, volumes, images, and slot freed)."
}

# Every volume compose creates for this stack, so an orphan can be mapped back
# to the project that made it. Keep in sync with docker-compose.yml's `volumes:`.
VOLUME_SUFFIXES="backend_node_modules backend_ws_node_modules frontend_node_modules frontend_ws_node_modules e2e_node_modules e2e_ws_node_modules postgres_data pgadmin_data"

# Compose names volumes "<project>_<suffix>" and built images "<project>-<service>",
# and neither is invertible in general — a project name has no delimiter of its own,
# so recovering one by stripping a suffix is a guess. These two only answer "is this
# shaped like one of ours at all", which costs nothing when wrong; liveness is
# decided by `live_artifacts` building the names forward instead.
is_our_volume() {
  local s
  for s in $VOLUME_SUFFIXES; do
    case "$1" in *"_$s") return 0 ;; esac
  done
  return 1
}

is_our_image() {
  case "$1" in *-backend|*-frontend) return 0 ;; *) return 1 ;; esac
}

# Projects still owning a registry entry. Anything else under the cs- prefix is
# an orphan: its worktree is gone, so no `rm` will ever reclaim it.
live_projects() {
  ensure_registry
  node -e 'const r=require(process.argv[1]);console.log(Object.keys(r).join("\n"))' "$REGISTRY" \
    | while IFS= read -r b; do [ -n "$b" ] && project_name "$b"; done
  # An empty registry ends the loop on a failed `read`, and under `set -e` that
  # status propagates through the caller's command substitution and kills the
  # script. Return success explicitly.
  return 0
}

# Every artifact name a registered worktree owns, composed FORWARD from the
# project name. Matching a candidate against this exact set is what keeps a
# misparse from ever deleting a live project's Postgres data — the direction
# compose's naming actually supports (#1452).
live_artifacts() {
  local p s
  live_projects | while IFS= read -r p; do
    [ -n "$p" ] || continue
    for s in $VOLUME_SUFFIXES; do printf '%s_%s\n' "$p" "$s"; done
    printf '%s-backend\n%s-frontend\n' "$p" "$p"
  done
  return 0
}

cmd_prune() {
  local apply=0
  for arg in "$@"; do [ "$arg" = "--yes" ] && apply=1; done

  local live; live="$(live_artifacts)"
  is_live() { [ -n "$live" ] && printf '%s\n' "$live" | grep -qxF "$1"; }

  local vols="" imgs="" skipped=0
  while IFS= read -r v; do
    [ -n "$v" ] || continue
    case "$v" in cs-*) ;; *) skipped=$((skipped + 1)); continue ;; esac
    if ! is_our_volume "$v"; then skipped=$((skipped + 1)); continue; fi
    is_live "$v" || vols="$vols$v
"
  done <<< "$(docker volume ls -q 2>/dev/null)"

  while IFS= read -r i; do
    [ -n "$i" ] || continue
    case "$i" in cs-*) ;; *) continue ;; esac
    if ! is_our_image "$i"; then continue; fi
    is_live "$i" || imgs="$imgs$i
"
  done <<< "$(docker images --format '{{.Repository}}' 2>/dev/null | sort -u)"

  local nv ni
  nv="$(printf '%s' "$vols" | grep -c . || true)"
  ni="$(printf '%s' "$imgs" | grep -c . || true)"

  # Every branch below is a full `if`: under `set -e` a bare `[ … ] && cmd` whose
  # test fails returns 1 and aborts the script.
  if [ "$nv" -eq 0 ] && [ "$ni" -eq 0 ]; then
    echo "Nothing to prune."
  else
    echo "Orphaned artifacts (no registry entry): $nv volume(s), $ni image(s)."
    if [ "$nv" -gt 0 ]; then printf '%s' "$vols" | sed 's/^/  volume /'; fi
    if [ "$ni" -gt 0 ]; then printf '%s' "$imgs" | sed 's/^/  image  /'; fi
  fi

  # Only cs-* is provably ours; pre-prefix projects and unrelated stacks are
  # reported, never removed, because the naming can't distinguish them.
  if [ "$skipped" -gt 0 ]; then
    echo "Skipped $skipped volume(s) outside the cs-* naming — inspect and remove by hand if they're yours."
  fi

  if [ "$apply" != 1 ]; then
    if [ "$nv" -gt 0 ] || [ "$ni" -gt 0 ]; then echo "Dry run. Re-run with --yes to remove."; fi
    return 0
  fi

  # A volume still attached to a running container fails to remove; that is the
  # safe outcome, so the failure is reported rather than forced — and reported
  # honestly, because "Pruned." over a failed `rm` is how a leak stays invisible.
  local failed=0
  if [ "$nv" -gt 0 ]; then printf '%s' "$vols" | xargs docker volume rm >/dev/null 2>&1 || failed=1; fi
  if [ "$ni" -gt 0 ]; then printf '%s' "$imgs" | xargs docker image rm >/dev/null 2>&1 || failed=1; fi
  if [ "$failed" -eq 1 ]; then
    echo "Pruned what it could — some artifacts are still in use by a running container. Stop it and re-run."
  else
    echo "Pruned."
  fi
}

cmd_ls() {
  ensure_registry
  local branches
  branches="$(node -e 'const r=require(process.argv[1]);console.log(Object.keys(r).join("\n"))' "$REGISTRY")"
  if [ -z "$branches" ]; then
    echo "No worktrees. Create one: ./.claude/skills/worktree/worktree.sh create <branch>"
    return
  fi
  printf '%-28s %-5s %-26s %-26s %s\n' BRANCH SLOT FRONTEND BACKEND STATUS
  while IFS= read -r branch; do
    [ -n "$branch" ] || continue
    local slot proj status
    slot="$(slot_of "$branch")"
    proj="$(project_name "$branch")"
    if docker compose ls --format json 2>/dev/null | grep -q "\"$proj\""; then
      status="running"
    else
      status="stopped"
    fi
    printf '%-28s %-5s %-26s %-26s %s\n' \
      "$branch" "$slot" \
      "http://localhost:$(port_for "$slot" 5173)" \
      "http://localhost:$(port_for "$slot" 4000)/api" \
      "$status"
  done <<< "$branches"
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    create) cmd_create "$@" ;;
    up)     cmd_up "$@" ;;
    down)   cmd_down "$@" ;;
    rm)     cmd_rm "$@" ;;
    prune)  cmd_prune "$@" ;;
    ls|"")  cmd_ls "$@" ;;
    *)      die "unknown command '$sub' (create|up|down|ls|rm|prune)" ;;
  esac
}

main "$@"
