#!/usr/bin/env bash
#
# worktree.sh — spin up isolated, parallel dev stacks, one per git worktree.
#
# Each worktree gets a port "slot" (1-9). Every port + the Compose project name
# is derived from the slot, so two worktrees never collide and each one gets its
# OWN Postgres volume (migrations in one are invisible to the others). Slot 0 is
# reserved for the main checkout on default ports.
#
#   ./.claude/skills/worktree/worktree.sh create <branch> [--up]   create worktree, assign slot, write .env
#   ./.claude/skills/worktree/worktree.sh up <branch>              docker compose up -d (build)
#   ./.claude/skills/worktree/worktree.sh down <branch>            docker compose down (keep volumes)
#   ./.claude/skills/worktree/worktree.sh ls                       table of worktrees, slots, URLs, status
#   ./.claude/skills/worktree/worktree.sh rm <branch>              down -v + remove worktree + free slot
#
set -euo pipefail

# Repo root = three levels up from this script's dir
# (.claude/skills/worktree/). Resolve symlinks for safety.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
WT_DIR="$ROOT/.claude/worktrees"
REGISTRY="$WT_DIR/registry.json"

MAX_SLOT=9

die() { echo "error: $*" >&2; exit 1; }

# Compose project name: lowercase, non-alnum -> '-', collapse repeats, trim.
project_name() {
  local b="$1"
  b="$(printf '%s' "$b" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
  printf 'cs-%s' "$b"
}

ensure_registry() {
  mkdir -p "$WT_DIR"
  [ -f "$REGISTRY" ] || echo '{}' > "$REGISTRY"
}

# Read the slot assigned to a branch, or empty string.
slot_of() {
  ensure_registry
  node -e 'const r=require(process.argv[1]); process.stdout.write(String(r[process.argv[2]]??""))' "$REGISTRY" "$1"
}

# Lowest free slot in 1..MAX_SLOT not present in the registry.
next_free_slot() {
  ensure_registry
  node -e '
    const r=require(process.argv[1]); const max=+process.argv[2];
    const used=new Set(Object.values(r).map(Number));
    for (let i=1;i<=max;i++) if(!used.has(i)){console.log(i);process.exit(0);}
    process.exit(1);
  ' "$REGISTRY" "$MAX_SLOT" || die "no free slots (max $MAX_SLOT worktrees). Run 'rm' on an unused one."
}

registry_set() {
  ensure_registry
  node -e '
    const fs=require("fs"); const f=process.argv[1];
    const r=require(f); r[process.argv[2]]=Number(process.argv[3]);
    fs.writeFileSync(f, JSON.stringify(r,null,2)+"\n");
  ' "$REGISTRY" "$1" "$2"
}

registry_del() {
  ensure_registry
  node -e '
    const fs=require("fs"); const f=process.argv[1];
    const r=require(f); delete r[process.argv[2]];
    fs.writeFileSync(f, JSON.stringify(r,null,2)+"\n");
  ' "$REGISTRY" "$1"
}

# Slot assignment is read-registry -> pick-lowest-free -> write-registry; two
# concurrent creates (e.g. parallel autodev runs) would race that window and
# collide on a slot. mkdir is atomic, so it serves as the mutex — no flock on
# stock macOS.
SLOT_LOCK=""
lock_slots() {
  ensure_registry
  SLOT_LOCK="$WT_DIR/.slot.lock"
  local waited=0
  until mkdir "$SLOT_LOCK" 2>/dev/null; do
    [ "$waited" -ge 30 ] && die "slot lock held for ${waited}s ($SLOT_LOCK); remove it if no create is running"
    sleep 1; waited=$((waited + 1))
  done
  trap 'unlock_slots' EXIT
}
unlock_slots() {
  [ -n "$SLOT_LOCK" ] && rmdir "$SLOT_LOCK" 2>/dev/null
  SLOT_LOCK=""
}

# Echo the port for (slot, base): base + slot*10.
port_for() { echo $(( $2 + $1 * 10 )); }

worktree_path() { echo "$WT_DIR/$1"; }

write_env() {
  local branch="$1" slot="$2" path="$3"
  local proj backend frontend pg pgadmin
  proj="$(project_name "$branch")"
  backend="$(port_for "$slot" 4000)"
  frontend="$(port_for "$slot" 5173)"
  pg="$(port_for "$slot" 5432)"
  pgadmin="$(port_for "$slot" 5050)"
  cat > "$path/.env" <<EOF
# Generated by .claude/skills/worktree/worktree.sh — worktree '$branch', slot $slot.
# Gitignored. Regenerate with: ./.claude/skills/worktree/worktree.sh create $branch
COMPOSE_PROJECT_NAME=$proj
BACKEND_PORT=$backend
FRONTEND_PORT=$frontend
POSTGRES_PORT=$pg
PGADMIN_PORT=$pgadmin
VITE_API_URL=http://localhost:$backend/api
EOF
}

print_ports() {
  local branch="$1" slot="$2"
  echo "  slot:     $slot"
  echo "  project:  $(project_name "$branch")"
  echo "  frontend: http://localhost:$(port_for "$slot" 5173)"
  echo "  backend:  http://localhost:$(port_for "$slot" 4000)/api"
  echo "  postgres: localhost:$(port_for "$slot" 5432)"
}

cmd_create() {
  local branch="${1:-}"; shift || true
  [ -n "$branch" ] || die "usage: worktree.sh create <branch> [--up]"
  local do_up=0
  [ "${1:-}" = "--up" ] && do_up=1

  local path; path="$(worktree_path "$branch")"
  local slot; slot="$(slot_of "$branch")"

  if [ -d "$path" ]; then
    [ -n "$slot" ] || die "worktree dir exists but no slot recorded; remove $path manually"
    echo "Worktree '$branch' already exists (slot $slot); refreshing .env."
  else
    lock_slots
    slot="$(next_free_slot)"
    # Reuse the branch if it already exists, otherwise create it from HEAD.
    if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$branch"; then
      git -C "$ROOT" worktree add "$path" "$branch"
    else
      git -C "$ROOT" worktree add "$path" -b "$branch"
    fi
    registry_set "$branch" "$slot"
    unlock_slots
  fi

  write_env "$branch" "$slot" "$path"
  echo "Worktree '$branch' ready:"
  print_ports "$branch" "$slot"

  if [ "$do_up" = 1 ]; then
    cmd_up "$branch"
  else
    echo "  start it: ./.claude/skills/worktree/worktree.sh up $branch"
  fi
}

cmd_up() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh up <branch>"
  local path; path="$(worktree_path "$branch")"
  [ -d "$path" ] || die "no worktree '$branch' (run: create $branch)"
  echo "Starting '$branch'…"
  ( cd "$path" && docker compose up --build -d )
  print_ports "$branch" "$(slot_of "$branch")"
}

cmd_down() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh down <branch>"
  local path; path="$(worktree_path "$branch")"
  [ -d "$path" ] || die "no worktree '$branch'"
  ( cd "$path" && docker compose down )
}

cmd_rm() {
  local branch="${1:-}"
  [ -n "$branch" ] || die "usage: worktree.sh rm <branch>"
  local path; path="$(worktree_path "$branch")"
  if [ -d "$path" ]; then
    ( cd "$path" && docker compose down -v ) || true
    # A half-torn-down dir (git worktree metadata already pruned) makes
    # `worktree remove` die with "not a working tree" — fall back to removing
    # the dir + pruning so the slot is still freed (the janitor relies on rm
    # never leaving a registry entry behind).
    git -C "$ROOT" worktree remove "$path" --force || { rm -rf "$path"; git -C "$ROOT" worktree prune; }
  fi
  registry_del "$branch"
  echo "Removed worktree '$branch' (containers, volumes, and slot freed)."
}

cmd_ls() {
  ensure_registry
  local branches
  branches="$(node -e 'const r=require(process.argv[1]);console.log(Object.keys(r).join("\n"))' "$REGISTRY")"
  if [ -z "$branches" ]; then
    echo "No worktrees. Create one: ./.claude/skills/worktree/worktree.sh create <branch>"
    return
  fi
  printf '%-28s %-5s %-26s %-26s %s\n' BRANCH SLOT FRONTEND BACKEND STATUS
  while IFS= read -r branch; do
    [ -n "$branch" ] || continue
    local slot proj status
    slot="$(slot_of "$branch")"
    proj="$(project_name "$branch")"
    if docker compose ls --format json 2>/dev/null | grep -q "\"$proj\""; then
      status="running"
    else
      status="stopped"
    fi
    printf '%-28s %-5s %-26s %-26s %s\n' \
      "$branch" "$slot" \
      "http://localhost:$(port_for "$slot" 5173)" \
      "http://localhost:$(port_for "$slot" 4000)/api" \
      "$status"
  done <<< "$branches"
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    create) cmd_create "$@" ;;
    up)     cmd_up "$@" ;;
    down)   cmd_down "$@" ;;
    rm)     cmd_rm "$@" ;;
    ls|"")  cmd_ls "$@" ;;
    *)      die "unknown command '$sub' (create|up|down|ls|rm)" ;;
  esac
}

main "$@"
