-- #1645 (epic #1644): the columns that let a SEEDED Item be a magic item.
-- Item has never had rarity, attunement or capabilities, so the catalog could
-- not express one at all — every magic item in the app today has to be authored
-- per-campaign. This removes that ceiling. Purely additive: every default is
-- inert, nothing reads these columns yet, and #1646 is what populates them by
-- merging CampaignItem rows in.
--
-- createdAt/updatedAt come along because serializeCampaignItem puts both on the
-- wire; promoting them now keeps #1646 a pure data move rather than a wire
-- change.
--
-- The ItemCapability column set is a VERBATIM copy of CampaignItemCapability,
-- which accumulated ~40 columns across five migrations (#545/#528/#543/#529/
-- #555) — it was generated by reading information_schema rather than
-- transcribed by hand, and item-capability-parity.integration.test.ts compares
-- the two tables directly so a future divergence fails loudly. #1646 copies
-- rows across with a straight INSERT … SELECT; a missed column there would
-- silently drop data for every DM-authored magic item.
--
-- Hand-written per the convention 20260801120000's header records: Prisma 7
-- prompts interactively on `migrate dev --create-only` in this checkout.

ALTER TABLE "Item" ADD COLUMN "rarity" "ItemRarity";
ALTER TABLE "Item" ADD COLUMN "requiresAttunement" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Item" ADD COLUMN "attunementPrereqKind" "AttunementPrereqKind";
ALTER TABLE "Item" ADD COLUMN "attunementPrereqValue" TEXT;
ALTER TABLE "Item" ADD COLUMN "isUnique" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Item" ADD COLUMN "dmNotes" TEXT;
ALTER TABLE "Item" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- @updatedAt is set by the Prisma client, not the database, so the datamodel
-- carries NO default here. The default exists only to backfill the 124 existing
-- catalog rows without a NOT NULL violation, and is dropped immediately — left
-- in place it is schema drift that `migrate diff` reports on every later change.
ALTER TABLE "Item" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Item" ALTER COLUMN "updatedAt" DROP DEFAULT;

CREATE TABLE "ItemCapability" (
    "id" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "kind" "CapabilityKind" NOT NULL,
    "description" TEXT,
    "target" "CapabilityTarget",
    "op" "CapabilityOp",
    "value" INTEGER,
    "targetKey" TEXT,
    "condition" TEXT,
    "valueDiceCount" INTEGER,
    "valueDiceFaces" INTEGER,
    "valueDamageType" TEXT,
    "activatedDuration" "ActivatedDuration",
    "activation" "ActivationType",
    "durationText" TEXT,
    "resourceCharges" INTEGER,
    "resourceKind" "ItemResourceKind",
    "resourcePeriod" "ItemResourcePeriod",
    "attackMode" "CapabilityCastStatMode",
    "attackValue" INTEGER,
    "castConcentration" BOOLEAN,
    "castLevel" INTEGER,
    "castResource" "CapabilityCastResource",
    "castUses" INTEGER,
    "dcMode" "CapabilityCastStatMode",
    "dcValue" INTEGER,
    "spellId" TEXT,
    "spellLevel" INTEGER,
    "spellName" TEXT,
    "cantBeSurprised" BOOLEAN NOT NULL DEFAULT false,
    "grantOn" TEXT,
    "grantType" TEXT,
    "grantValue" TEXT,
    "grantValueKind" TEXT,
    "chargeCost" INTEGER,
    "maxCharges" INTEGER,
    "rechargeBonus" INTEGER,
    "rechargeDiceCount" INTEGER,
    "rechargeDiceFaces" INTEGER,
    "rechargeTrigger" "ItemResourcePeriod",

    CONSTRAINT "ItemCapability_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ItemCapability_itemId_idx" ON "ItemCapability"("itemId");

ALTER TABLE "ItemCapability" ADD CONSTRAINT "ItemCapability_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "Item"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
